### ISSUE TITLE
Can't use qsv_av1_10bit 'Ffmpeg encode_sample exit code Some(1)'

### ISSUE THREAD

**Issue by ssjbardock** [alexheretic/ab-av1#103]
I have tried running the command "ab-av1 crf-search -e qsv_av1_10bit" (plus -i info) and despite trying multiple ffmpeg builds, including compiling my own including intel-qsv, I get the error 'Ffmpeg encode_sample exit code Some(1)'.

Any fix for this? Trying to determine settings for Av1 QSV 10bit encodes. Thanks!

Specs:
5950x
64GB Ram
Intel Arc A770

**Comment by ssjbardock** [comment]
Found that the script needs the preset as numerical instead of following the intel 'speed/quality' scale.

**Comment by alexheretic** [comment]
Seems similar to #107, so perhaps a similar change would work for this too?

**Comment by jsmcconn** [comment]
The similar rate control parameter for qsv would be `-global_quality`, see [here](https://trac.ffmpeg.org/wiki/Hardware/QuickSync).

This seems to work for h264_qsv and hevc_qsv, however my Tiger Lake cpu doesn't support the av1_qsv encoder, and also it appears rate control is not yet implemented in the encoder.

This encoder is only a couple months old, so it probably still needs some work ([commit](https://github.com/FFmpeg/FFmpeg/commit/dc9e4789a3b504c08c8cd24e990aa692dde50bc6)).

```
C:\Video>ffmpeg -i ToS-4k-1920.mov -c:v av1_qsv -an -global_quality 25 out_av1.mkv
...
[av1_qsv @ 0000025f24083100] Selected ratecontrol mode is unsupported
[av1_qsv @ 0000025f24083100] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
```

Would be reasonable to add support for `-global_quality` for qsv encoders, but av1 still wouldn't work yet.

**Comment by Rodeo314** [comment]
FWIW, it doesn't help that global_quality can map to 4 different QSV rc modes (CQP, ICQ, ICQ_LA or QVBR) depending on other parameters, making ffmpeg's error output above not particularly helpful.

I wonder if something above it (that you cut out) could provide a clue as to what rc mode it actually attempted to use?

**Comment by alexheretic** [comment]
Closing as I'm missing clear actions to take here and cannot investigate this hw vcodec myself. Happy to re-open when we have more info.

**Comment by BankaiNoJutsu** [comment]
Do you have multiple Intel GPUs? As in integrated + dedicated?
