### ISSUE TITLE
Some odd results with lower than expected VMAF scores

### ISSUE THREAD

**Issue by iPaulis** [alexheretic/ab-av1#108]
Hi, I'm testing some av1 parameters and then getting their vmaf results.
Lately I found this really nice tool called FFMetrics in github which is a GUI for ffmpeg that offers multiple assessment calculations plotting the scores in a frame graph.
It can manage a queue of distorted files, so I tested it with some files I had already calculated with ab-av1, and the results are not even close.
Now I'm trying to understand where the differences come from, as the results from ab-av1 vmaf are quite lower than expected.

It is a 5 minute video part of a movie that has some easier scenes, but then also very heavy snow and a good amount of grain, which could make it quite complicated to encode and interesting to test, so I understand that the final results are lower than the estimate (I increased the samples to compensate), but the difference is quite high.

All the estimations with different parameters were something similar to this:
> ab-av1 sample-encode  --scd true --svt tune=0 --svt enable-overlays=1 --svt enable-tf=0 --svt irefresh-type=1 --svt enable-qm=1 --pix-format yuv420p10le --vmaf pool=harmonic_mean -i '.\00100 (cap11)-011.mkv' --crf 17 --preset 6
>  
> VMAF 95.80 predicted video stream size 155.63 MiB (20%) taking 11 minutes

All of the vmaf results where greater than 95%, which makes sense for crf 17 in svtav1.
![Captura de pantalla 2023-01-11 001537_AV1parameters](https://user-images.githubusercontent.com/11468889/212588640-35fc485e-db78-4c1d-abcd-a8a79ec9910b.png)

As they were a bunch of encodes, I used Handbrake v1.6.0 to queue and encode them in svtav1 v1.4.1, the same as the version implemented in ffmpeg used by ab-av1, then I checked the vmaf scores, all around 80%.
![Captura de pantalla 2023-01-11 061356_AV1 parameters](https://user-images.githubusercontent.com/11468889/212589974-4ce34e1a-75f6-4af9-b106-54d034e2fd2f.png)

I also encoded the result with my preferred parameters with ab-av1:
`ab-av1 encode -i ".\00100 (cap11)-011.mkv" --crf 17 --preset 6 --pix-format yuv420p10le --svt tune=0 --svt enable-overlays=1 --svt passes=2 --svt enable-qm=1`
Weirdly the vmaf results in this case were even lower, which does not make sense for such crf level.

> ab-av1 vmaf --vmaf pool=harmonic_mean --reference '"G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (cap11)-011.mkv"' --distorted '"G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (cap11)-011.av1_ffmpeg_tune0 ov1 2pass qm1.mkv"'
> 
> 73.88504

Now, these are the results of the same files in FFMetrics:
![Captura de pantalla 2023-01-16 042233](https://user-images.githubusercontent.com/11468889/212593592-ecd328f1-f836-44a2-801d-8c26b692da22.png)

In case it helps identify the differences, this is the ffmpeg command FFMetrics is running in the background, from its log:
`ffmpeg.exe -hide_banner -nostdin -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (Cap11)-011 av1_rf17_tune0 2pass ovlay1 qm1.mkv" -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.mkv" -lavfi [0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:log_fmt=json:log_path='C\:/Users/iPaulis/AppData/Local/Temp/FFMetrics/b2e4933c-d157-48ea-b8e2-45df67db999c.log':pool=Mean:model=version=vmaf_v0.6.1 -f null -`

Those are quite different results compared to the previous vmaf results in ab-av1, and seem more consistent with crf17.
The harmonic means are naturally lower, but still higher than ab-av1 vmaf results:
> VMAF-MeanH
> 86.030135
> 86.036957
> 85.930127
> 85.949970
> 85.970850
> 86.125711
> 86.036387
> 85.652825
> 85.858755
> 95.714059

This is the plotted vmaf graph (visual quality holds up very well even in the snowy grainy part):
![VMAF](https://user-images.githubusercontent.com/11468889/212594906-936deba9-0e23-4cf2-8d74-ebd6a7804c2e.png)
Below is the plotted PSNR graph (even if the score is more affected in this metric by the complex part, it is not that noticeable visually):
![PSNR](https://user-images.githubusercontent.com/11468889/212601315-42ffb0cb-a83d-429f-a045-9cc43f2065ae.png)

Besides, I notice 2 strange things seeing all these results, apart from the vmaf score differences (80 vs almost 89).
Firstly, there is a huge quality difference between handbrake and ab-av1 encodes (even visually noticeable), although they were encoded with the same svtav1 version, so I don't understand what is going on. As shown in the graph, handbrake's encode is doing very weird spikes unlike ab-av1, which varies according to the scene complexity but remains more consistent. 
I should probably open an issue in their github with the comparison to ab-av1 to see if they can figure out what is happening in that graph because it is greatly impacting the encoding quality. Any idea?

Secondly, FFMetrics' vmaf score for the file encoded in ab-av1 surprisingly is not lower that handbrake's encodes as suggested by ab-av1 vmaf results (hb 80,3 vs ab-av1 73,9 both according to ab-av1 vmaf), but higher (hb 88,8 vs ab-av1 95,7 both according to FFMetrics). Again, FFMetrics' results seem more realistic for crf 17, also supported by PSNR and SSIM results, and it even matches the ab-av1 estimated vmaf results pretty accurately.

I wonder why the FFMetrics' results seem to be more accurate and why the ab-av1's encode is so much better than handbrake's.

**Comment by alexheretic** [comment]
sample-encode is approximate, unless your using a full pass. harmonic mean doesn't really have as much effect with sample-encode, unless doing full pass / lots of samples.

You seem to be comparing mean vs harmonic-mean so it makes sense the latter is lower.

Otherwise I'm not sure how these other programs are encoding/vmafing so i can't really explain the difference exactly.

**Comment by iPaulis** [comment]
Ok, I think I figured it out. The vmaf command used by FFMetrics is this one:

> ffmpeg.exe -hide_banner -nostdin -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.av1_ffmpeg_tune0 ov1 2pass qm1.mkv" -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.mkv" -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:log_fmt=json:log_path='C\:/Users/iPaulis/AppData/Local/Temp/FFMetrics/e81bf1ed-b23c-48fd-8abf-5f71d293e49c.log':pool=Mean:model=version=vmaf_v0.6.1" -f null -

When I delete this part `[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]` it gives the same vmaf result as ab-av1. I don't fully understand what it does, it seems to set a common timebase and timestamp for the reference and distorted files, so I don't know if it is better to have it or not. Some people say that different containers have different timebase, so the frames may have different timestamps and when comparing them with vmaf they would jitter and alter the results. If that is the case, then it could be recommended to run the command this those parameters, but I'm not sure.

However, apart from this, in ab-av1 whether I try to set `--vmaf pool=harmonic_mean` or `--vmaf pool=mean` or even leave it by default, it does not change the results at all (in any instance where that vmaf parameter could be used), so I guess there is an issue there.

**Comment by iPaulis** [comment]
### VMAF command examples for the same file at CRF17 svtav1, 1080p 24fps 3545 kb/s

#### Default ab-av1 values
`ab-av1 vmaf --reference "G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (cap11)-011.mkv"' --distorted '"G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (Cap11)-011 av1_rf17_tune0 2pass ovlay1 qm1.mkv"`
VMAF score: 80.34283
Too low score in my opinion for crf 17 in svtav1.

#### Default ffmpeg values
`ffmpeg.exe -hide_banner -nostdin -i "G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (Cap11)-011 av1_rf17_tune0 2pass ovlay1 qm1.mkv" -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.mkv" -lavfi "libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 79.030344
Even worse result, it does not make any sense.

#### With AVTB timebase
`ffmpeg.exe -hide_banner -nostdin -i "G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (Cap11)-011 av1_rf17_tune0 2pass ovlay1 qm1.mkv" -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.mkv" -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 88.919527
It could be possible, but with a bitrate of 3545 kb/s for a 1080p file in svtav1, I think it is still too low, it should be plenty of bitrate for this encoder.

#### With 1/AVTB timebase
`ffmpeg.exe -hide_banner -nostdin -i "G:\Pelis\Saga Harry Potter\6 Harry Potter y el Misterio del Príncipe (2009)\00100 (Cap11)-011 av1_rf17_tune0 2pass ovlay1 qm1.mkv" -i "G:/Pelis/Saga Harry Potter/6 Harry Potter y el Misterio del Príncipe (2009)/00100 (cap11)-011.mkv" -lavfi "[0:v]settb=1/AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=1/AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 95.647760
I believe these parameters should be the correct ones, they make the most sense for this encoder, crf and bitrate.

The results are significantly different and could have a noticeable impact in the behavior of ab-av1 as it relies in vmaf calculations for many functions. It would be worth to test it out.

**Comment by alexheretic** [comment]
Interesting, i have noticed some cases where the vmaf was significantly different for different containers. I'll look into testing these timebase adjustments when i get a chance.

**Comment by iPaulis** [comment]
Notice that in my testing all files were in the same container, mkv, but the vmaf results were still very different with these files. In some other files this does not happen, or results differ less.
Checking mediainfo I've seen that in some cases the FPS is altered in the encoded file from ab-av1.
Original: 23,976 (24000/1001) FPS
Encoded: 23,976 (23976/1000) FPS

Then, the timestamp differences could highly affect the vmaf results, but they could be corrected setting an appropriate timebase. However, not all the affected files show a different FPS, but some of them still get a different result by changing the timebase. So an altered FPS might signal this issue, but an unaltered one might not mean it is accurate. Or FPS may be completely unrelated to this, I'm not sure.

So far I've observed that between default (blank), AVTB and 1/AVTB timebase, in the files with inconsistent vmafs the latter option gives what seems the most accurate result, and in the more consistent files, the 3 timebases essentially give the same results, so it does not damage the score or introduce inaccuracies, but leaving it default might in some cases, as shown above.
I think 1/AVTB might be a win-win, you may test it yourself with some of your files.

**Comment by iPaulis** [comment]
I downloaded an [open sample video](http://ftp.nluug.nl/pub/graphics/blender/demo/movies/Blender_reel_2013.mov) to try to reproduce the issue and it works as a representative sample, consistently giving inaccurate vmaf scores time after time, whatever the encoder or crf used to encode it (I tried x265 and svtav1 with several crf). I also tried with other samples from there, like Big Buck Bunny, and also show vmaf inconsistencies depending on the parameters used to run the command.

Steps to reproduce:
- Encode sample like this: `ab-av1 encode -i I:\test\Blender_reel_2013.mov --crf 30 --preset 6 --pix-format yuv420p10le`
- Test with vmaf commands:

Default timebase, not set: `ffmpeg.exe -hide_banner -nostdin -i $distorted -i $reference -lavfi "libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 96.287719, which seems correct.

Timebase AVTB: `ffmpeg.exe -hide_banner -nostdin -i $distorted -i $reference -lavfi "[0:v]settb=AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 79.786164, this is definitely wrong.

Timebase 1/AVTB: 	`ffmpeg.exe -hide_banner -nostdin -i $distorted -i $reference -lavfi "[0:v]settb=1/AVTB,setpts=PTS-STARTPTS[main];[1:v]settb=1/AVTB,setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1" -f null -`
VMAF score: 96.287909, this seems correct again.

ab-av1 vmaf: `ab-av1 vmaf --vmaf pool=harmonic_mean --reference 'I:\test\Blender_reel_2013.mov' --distorted 'I:\test\Blender_reel_2013.av1.mkv'`
VMAF score: 96.28791, seems a rounded score of the ffmpeg 1/AVTB calculation.

For what I've seen in my tests, I've found vmaf problems from mkv to mkv, from mp4 to mp4, from mp4 to mkv, from mov to mkv, among other containers. 
In most of the tests ab-av1 vmaf seems to usually give more accurate results than default ffmpeg vmaf command, but very similar to ffmpeg with 1/AVTB parameter.

**Comment by alexheretic** [comment]
I can't say I fully understand the timebase adjustment but I've made a branch that applies your suggested filters to the vmaf invocation. You can give it a try and see if it improves your test cases if you like.

I'll run some more tests myself when I have some time.

**Comment by alexheretic** [comment]
Unfortunately I found a significant regression in one of my test cases https://github.com/alexheretic/ab-av1/pull/109#issuecomment-1396895377

**Comment by iPaulis** [comment]
I found a regression too in one of my tests (BBB), so although it fixes other cases, it is not a definitive solution.

I'm reading documentation and some explanation in stackoverflow about how timebase and timestamps work, such as [this](https://stackoverflow.com/questions/43333542/what-is-video-timescale-timebase-or-timestamp-in-ffmpeg) and [this](https://stackoverflow.com/questions/58261344/what-does-ffmpegs-setpts-filter-do-exactly), I don't fully understand it, but it helped me get a better idea of the issue.

There are 2 parameters: timebase ([settb](https://ffmpeg.org/ffmpeg-filters.html#settb_002c-asettb), default value intb, which is input time base) and timestamp ([setpts](https://ffmpeg.org/ffmpeg-filters.html#setpts_002c-asetpts), but docs don't state what the default value is).

So far I've seen that some timebase and timestamp combinations work for some files and not for others, but both parameters do affect the results, so I'm trying each parameter independently to figure out which one introduces the regression for each case. I'll add your sample file into my tests.

When I have some time I would like to test more combinations more thoroughly to try to find a universal solution if possible.

**Comment by iPaulis** [comment]
After many many tests with inconsistent results, I think I finally found a working solution that has given me reliable results with the 6 sample files I've been testing with (including the Sony HDR 4k sample).

This kind of problem has previously occurred to some people trying to calculate vmaf scores with inputs that are not perfectly in sync. In seems that encoding a video the output could sometime be a frame off, and some other times, especially when changing the container, the timebase of each container could be different, so the frame timestamps would not match, even if the number of frames is the same. More info about that [here](https://myakamai.force.com/customers/s/article/MediaDeliveryTimestamppitfallswhenusinglibvmaffilterwithFFMPEG20210205164021?language=en_US).

With ffmpef or ffprobe we can check the timebase info of the files in the following values:
- tbn = the time base in AVStream that has come from the container
- tbc = the time base in AVCodecContext for the codec used for a particular stream
- tbr = tbr is guessed from the video stream and is the value users want to see when they look for the video frame rate

When these kind of sync mismatches happen vmaf results in a wrong score.

This problem was reported in the vmaf github (examples, [here](https://github.com/Netflix/vmaf/issues/611) and [here](https://github.com/Netflix/vmaf/issues/629)), so vmaf developers updated their documentation to address this issue.
In the [official docs](https://github.com/Netflix/vmaf/blob/master/resource/doc/ffmpeg.md) they recommend adding `-r` before each input to set the framerate and `PTS-STARTPTS` to sync the presentation timestamps of the 2 videos.

The final command would be something like this:
`ffmpeg.exe -hide_banner -nostdin -r $framerate -i $distorted -r $framerate -i $reference -lavfi '[0:v]setpts=PTS-STARTPTS[main];[1:v]setpts=PTS-STARTPTS[ref];[main][ref]libvmaf=eof_action=endall:n_threads=15:pool=Mean:model=version=vmaf_v0.6.1' -f null -`

And indeed, it works, or at least it fixed the vmaf scores of my tests with no regressions.

So ab-av1 would need to get the framerate of the input files and then use those values in the vmaf command, something like this results in the exact framerate value: 
`ffprobe -v 0 -of csv=p=0 -select_streams v:0 -show_entries stream=r_frame_rate $inputfile`

Although I have used rounded numbers and the vmaf results were still correct, the `-r` parameter accepts fractions like `-r 24000/1001` to set exact framerates, which would be ideal.

Please @alexheretic, test this solution as suggested in the vmaf documentation and try to see if the issue also gets fixed in the files where you found the vmaf inconsistencies the same way it did with mine.

**Comment by alexheretic** [comment]
Nice one! I'll implement this in a pr when i get a moment.

**Comment by alexheretic** [comment]
#115
