### ISSUE TITLE
--encoder hevc_nvenc "Error: Failed to find a suitable crf"

### ISSUE THREAD

**Issue by ronnylov** [alexheretic/ab-av1#110]
Hi!

I tried following with my GTX 1070 GPU.

`ab-av1 auto-encode --encoder hevc_nvenc -i ../'Små och stora brott.mkv'
Encoding '../Små och stora brott.hevc_nvenc.mkv'
  Searching 00:09:26 #################################################################### (crf 10, VMAF 94.34, size 67%)Error: Failed to find a suitable crf`

Questions: 
Is the encoder not able to reach VMAF 95 at best setting or what is the reason for the error?
Are there some options to improve quality using my GPU?
Looking att ffmpeg documentation it seems that preset slow can be used with hevc_nvenc.
Tried it but got following:

ab-av1 auto-encode --encoder hevc_nvenc -i ../'Små och stora brott.mkv'--preset slow
error: Found argument 'slow' which wasn't expected, or isn't valid in this context

Usage: ab-av1 auto-encode [OPTIONS] --input <INPUT>

For more information try '--help'

Then I tried --preset 4 but got the same type of error as above.
Is it some method to pass options to ffmpeg like "--preset slow" from ab-av1?

Where can I find documentation regarding [OPTIONS]?

**Comment by alexheretic** [comment]
> Is the encoder not able to reach VMAF 95 at best setting or what is the reason for the error?

Yes the search reached the lowest "crf" (actually maps to ffmpeg -cq for nvenc) which is `10` by default. You can try allowing lower values with `--min-crf X`.

> ab-av1 auto-encode --encoder hevc_nvenc -i ../'Små och stora brott.mkv'--preset slow
> error: Found argument 'slow' which wasn't expected, or isn't valid in this context
> 
> Usage: ab-av1 auto-encode [OPTIONS] --input
> 
> For more information try '--help'
> 
> Then I tried --preset 4 but got the same type of error as above.
> Is it some method to pass options to ffmpeg like "--preset slow" from ab-av1?

You can use `--preset slow`. Are you sure you are entering it correctly? That error "Found argument 'slow'" indicates maybe the "--preset" didn't have a space before it or was missing.

**Comment by ronnylov** [comment]
Yes you are right I missed a space before --preset. Adding the space solved the problem with the error message.

Found this:
https://gist.github.com/nico-lab/c2d192cbb793dfd241c1eafeb52a21c3
There are a lot of presets. So I will try `--preset p7` to get "slowest (best quality)" and if necessary set a lower --min-crf

I decided to try crf-search instead of auto-encode to see VMAF scores at different crf values. 
It seems I get same VMAF score and file size estimation no matter of crf value.

```
ab-av1 crf-search --encoder hevc_nvenc -i ../'Små och stora brott.mkv' --preset p7 --min-crf 4 --max-crf 26
- crf 15 VMAF 94.36 (67%)
- crf 9 VMAF 94.36 (67%) (cache)
- crf 4 VMAF 94.36 (67%)
  00:06:34 ############################################################################################################## (sampling crf 4, eta 0s)Error: Failed to find a suitable crf
```

Tried it again without entering min and max crf

```
ab-av1 crf-search --encoder hevc_nvenc -i ../'Små och stora brott.mkv' --preset p7
- crf 32 VMAF 89.45 (14%) (cache)
- crf 21 VMAF 94.36 (67%) (cache)
- crf 10 VMAF 94.36 (67%) (cache)
  00:00:00 ############################################################################################################# (sampling crf 10, eta 0s)Error: Failed to find a suitable crf
```
So it seems quality is maxed out at VMAF 94.36 and 67%. Perhaps hevc_nvenc encoder is not better than this with my GPU. I guess it is pretty close to VMAF 95 so propably acceptable quality anyway. I can try h264_nvenc instead.

```
ab-av1 crf-search --encoder h264_nvenc -i ../'Små och stora brott.mkv' --preset p7
- crf 32 VMAF 88.68 (12%)
- crf 21 VMAF 95.11 (81%)
- crf 22 VMAF 94.72 (70%)
  00:09:27 ############################################################################################################# (sampling crf 22, eta 0s)
Error: Failed to find a suitable crf
```
Well here it looks like VMAF is OK at crf 21 but 81% file is above limit for making it worth compressing it any more than original file. crf 22 h264 is about similar quality and file size as with hevc. I think I will do some more tests using ffmpeg or nvencc directly to see if I can find any encoding settings that work better. 

Maybe I should buy some other GPU like Intel Arc A380 that can do AV1 also and probably better at hevc encoding than my old GTX 1070. I like having the option to use the GPU to encode video but only if it get acceptable quality vs file size. CPU encoding is another option. Had some problem playing AV1 on my devices but could try x265 to make hevc.

**Comment by alexheretic** [comment]
That looks like the crf (-cq) is capping at ~21 with all the lower values yielding the same. That seems odd but I don't have much experience using the nvenc encoders, perhaps that is expected?

I would definitely also try libx265 this can be quite fast if you have a decent CPU.

**Comment by ronnylov** [comment]
Perhaps my original video was already good compressed and that is why it is difficult to make it smaller without decreasing quality. And maybe that is what I needed to know in this case. Anyway it is a great tool, I like it very much.

```
ab-av1 crf-search --encoder libx265 -i ../'Små och stora brott.mkv' --preset fast
- crf 28 VMAF 82.66 (3%)
- crf 19 VMAF 91.84 (22%)
- crf 10 VMAF 96.28 (156%)
- crf 12.6 VMAF 95.38 (100%)
- crf 13.3 VMAF 95.09 (87%)
- crf 13.5 VMAF 95.00 (84%)
  00:38:17 ########################################################################################################### (sampling crf 13.5, eta 0s)Error: Failed to find a suitable crf
```

I will make a final crf search using libx265 --preset slow
But I am leaning to the conclusion this video was not worth trying to compress more, better keep the original to keep quality.
