### ISSUE TITLE
ab-av1 arg to fix ffmpeg Timestamps are unset in a packet for stream 0

### ISSUE THREAD

**Issue by Werve** [alexheretic/ab-av1#111]
It seems that ffmpeg cannot extract from this video file.

```
ab-av1 crf-search -e libsvtav1  -i "E:\Vid\test.avi"  --preset 6 --thorough --vmaf '"model_path=C\:/Users/Ant/.cargo/bin/vmaf_v0.6.1.json"' --min-vmaf 100 --vmaf pool=harmonic_mean

Searching for VMAF: 100
=> preset 6
  00:00:00 ################################################################################### (sampling crf 32, eta 0s)Error: ffmpeg copy exit code Some(1)
ffmpeg version 5.1-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, avi, from 'E:\Video\test.avi':
  Metadata:
    software        : VirtualDubMod 1.5.4.1 (build 2178/release)
    IAS1            : ???
  Duration: 01:47:30.60, start: 0.000000, bitrate: 910 kb/s
  Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 608x336 [SAR 1:1 DAR 38:21], 25 fps, 25 tbr, 25 tbn
  Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 104 kb/s
Output #0, matroska, to 'E:\Video\test.sample627+500f.mkv':
  Metadata:
    software        : VirtualDubMod 1.5.4.1 (build 2178/release)
    IAS1            : ???
    encoder         : Lavf59.27.100
  Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 608x336 [SAR 1:1 DAR 38:21], q=2-31, 25 fps, 25 tbr, 1k tbn
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[matroska @ 0000020af0e48680] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 0000020af0e48680] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
frame=    1 fps=0.0 q=-1.0 Lsize=       1kB time=-00:10:26.99 bitrate=N/A speed=N/A
video:15kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

Searching online passing ffmpeg arg `-fflags +genpts` would solve https://video.stackexchange.com/questions/24462/timestamps-are-unset-in-a-packet-for-stream-0-this-is-deprecated-and-will-stop but how to pass the "+" arg on ab-av1?
There is a way to log the ffmpeg command ab-av1 sent? (the error is almost instant so i cannot check on task manager), I already tried `--enc loglevel=debug` but the output seems ignore that. Same with `--enc report`

**Comment by Werve** [comment]
With external tools i managed to log the start/end of process and the command args. Seems like the process and the error is generated by the invocation of ffprobe.exe so it ignore the --enc args because ffmpeg.exe is not yet started. So at the moment is not possible process in one go with ab-av1 those files that require ffmpeg arg -fflags +genpts.

**Comment by alexheretic** [comment]
yeah old .avi files fail to create the samples with this. We could detect
this error and apply the workaround, but is it always desired?

A workaround is to -c copy convert them to .mp4 with ffmpeg first. Though
you may find old lower res xvid are unlikely to be able to re-encoded very
efficiently anyway.

**Comment by Werve** [comment]
I previously tried to copy/change to mkv with MKVToolNix then re-run ab-av1 but there are the same error.
So I think you first need to run that flag with ffmpeg to generate a compatible file, not just change the container.

Also, if any other similar problems arise that can be solved with other arguments in ffmpeg I noticed that ab-av1 invokes ffprobe first (to look up the duration I suppose) and if an error is encountered it does not proceed. 
Perhaps it would be better to report in this case the ffprobe response with -loglevel debug or -report to elaborate (or at least report the string of the executed invocation).

**Comment by alexheretic** [comment]
avi -> mp4 specifically had worked well for me where mkv hasn't. I'm not
sure why tbh.

I've also seen both work but mkv get very poor vmaf scores, where mp4 works
fine.

I'm just not 100% sure what is the best way to handle all avi is, so I'm
not sure what workarounds should be put into code.

**Comment by Werve** [comment]
Yes the ffmpeg -> mp4 seems to work even without the additional args `-fflags +genpts` , but with multiple info error "[mp4 @ 0000022c00087c00] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly".

So I could just always use `-o name.mp4` and then maybe change to mkv.

**Comment by Werve** [comment]
Just for info to who could have the same error.
After more test seems I can check if a file require that fix (-fflags +genpts) with the exit status of this:
`ffmpeg -i "test.avi" -vcodec copy -acodec copy -to 1 -f matroska NUL || echo Fix Needed`
