### ISSUE TITLE
Feature request - copy all subtitle tracks

### ISSUE THREAD

**Issue by BankaiNoJutsu** [alexheretic/ab-av1#112]
Hello,

Would it be possible to add an option to copy all subtitle tracks if more than one is present?

Currently only the first seems to be copied.

Additionally the default track should be copied as well

**Comment by alexheretic** [comment]
Thanks for raising this. I think this comes from ffmpeg's default behaviour, but I agree it makes sense that all subs & attachments be preserved. I'll take a look when I get some time.

**Comment by BankaiNoJutsu** [comment]
Cool!

Something like this should work:
-i output_of_ab-av1 -i original_file -map 0:v -map 1 -map -1:v -c copy

mapping the video from ab-av1 result, and copying the rest from original file

If audio is being converted with --acodec this would need to be adapted though

**Comment by BankaiNoJutsu** [comment]
It seems that multiple audio tracks are also ignored, only the first one is copied.

**Comment by BankaiNoJutsu** [comment]
So just adding:
        .arg2("-map", "0")
after
        .arg2("-i", input)
works for copying all files, including converting to AAC for example

**Comment by alexheretic** [comment]
Yep nice and easy thanks! This was in the back of my mind to check after I merged the old svt-av1 & ffmpeg paths together but I didn't get round to it.
