### ISSUE TITLE
Strange error, cannot find it's cause (code: 145, kind: DirectoryNotEmpty)

### ISSUE THREAD

**Issue by BankaiNoJutsu** [alexheretic/ab-av1#114]
Hello,

I regularly get this error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 145, kind: DirectoryNotEmpty, message: "The directory is not empty." }', src\temporary.rs:52:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I cannot really grasp why it's throwing this.

For context, the input and output are both on a CIFS/SMB share, so i was wondering if latency could trigger this. i.e deleting sample files not being instant.

Do you have any other idea i could explore?

Cheers!

**Comment by alexheretic** [comment]
Thanks, this is just some slightly unfinished code where I left the panics in.
