### ISSUE TITLE
auto-encode fails to start encode

### ISSUE THREAD

**Issue by marcin-przywoski** [alexheretic/ab-av1#117]
Hi,

I'm having an issue with the auto-encode option which worked fine on v0.7. I'm using a powershell script which processes several files at the same time using ab-av1 and while te v.0.7 works fine the latest one v0.7.2 does not. It appears that it does not start the encode when the right crf has been found - I'm seeing a glimpse of that when the file already stored in cache just pops up in the console and closes down instantly even though from what I saw there was a correct crf for my required vmaf score. When I went back to v.0.7 issue disappeared.

Does anyone know what may be the issue here?

**Comment by marcin-przywoski** [comment]
One additional note here - it appears that it happens almost solely with very small resolution files - most of them were 720p

**Comment by alexheretic** [comment]
Thanks for the report. Can you include the ab-av1 output when it's failing, is there a failure message?

Also if possible can you provide a file and your arguments so I can reproduce this?

**Comment by marcin-przywoski** [comment]
That's the command I use in a loop in Powershell :
Start-Process -FilePath "ab-av1" -ArgumentList "auto-encode --min-vmaf 90 --preset 6 --svt lp=10 --svt pix_fmt=yuv420p10le -i `"$oldfile`" -o `"$newfile`"" -Wait

It's not really giving me any error messages. It just stops processing instantly even though it has shown that a suitable crf exists

**Comment by alexheretic** [comment]
Can you try running it directly on the cli? There should be some output at the end whether it succeeds or falls.

**Comment by marcin-przywoski** [comment]
It appears that it's related to pixel format, that's what I got when I tried to run it in terminal, removing the pixel format parameter did not fix it :

Error: ffmpeg encode exit code 1
---stderr---
c --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221228
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 55.103 / 59. 55.103
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 53.100 /  8. 53.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002c55f95ad80] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Filmiki\Szkolna Na Celowniku\Szkolna Na Celowniku - 2020-07-17 - Alfabeta #8 Major i bigos pod Grunwaldem.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    artist          :
    album           :
    comment         : www.mediahuman.com
    genre           :
    title           : Alfabeta #8 Major i bigos pod Grunwaldem
    encoder         : Lavf59.16.100
  Duration: 00:02:18.00, start: 0.000000, bitrate: 2635 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 2499 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x0]: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 480x360 [SAR 1:1 DAR 4:3], 90k tbr, 90k tbn (attached pic)
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> av1 (libsvtav1))
  Stream #0:1 -> #0:1 (aac (native) -> opus (libopus))
  Stream #0:2 -> #0:2 (mjpeg (native) -> av1 (libsvtav1))
Press [q] to stop, [?] for help
[swscaler @ 000002c562440580] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002c562789ac0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002c561795fc0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 000002c562780540] deprecated pixel format used, make sure you did set range correctly
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:       SVT-AV1 Encoder Lib v1.4.1-5-g91832ee2
Svt[info]: SVT [build]  :       GCC 12.2.0       64 bit
Svt[info]: LIB Build date: Dec 24 2022 21:24:37
Svt[info]: -------------------------------------------
[libsvtav1 @ 000002c5616a0740] Specified chroma sample location center is unsupported on the AV1 bit stream level. Usage of a container that allows passing this information - such as Matroska - is recommended.
Svt[error]: Instance 1: The maximum allowed frame rate is 240 fps
[libsvtav1 @ 000002c5616a0740] Error setting encoder parameters: bad parameter (0x80001005)
Error initializing output stream 0:2 -- Error while opening encoder for output stream #0:2 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
------------

**Comment by alexheretic** [comment]
yeah the svt pix_fmt arg seems wrong, and indeed this pixel format is already the default here using av1, so need to specify it (there's also a --pixel-format option for overriding it).

What error do you get without any --svt args?

I'm not sure why v0.7.0 would have worked here since it will call ffmpeg libsvtav1 in the same way iirc.

**Comment by marcin-przywoski** [comment]
As I've wrote above - removing there parameter did not fix it, nor using the --pixel-format one

**Comment by alexheretic** [comment]
ah i think i understand. stream 2, the mjpeg one, previously would have been dropped. But in v0.7.2 all streams go into the output. In this case that stream is failing to be encoded by libsvtav1.

In this case it would probably make more sense to copy that additional video stream rather than re-encode it or drop it. Currently there is no option for that. We should have better support for multi vstream files.

**Comment by alexheretic** [comment]
This should be fixed in the next release with any other "non-main" video streams being copied to the output rather than encoded.
