### ISSUE TITLE
Encode stuck with no progress.

### ISSUE THREAD

**Issue by darkstego** [alexheretic/ab-av1#123]
I have noticed that running the `encode` command on some files results on the encode starting with no progress ever being made. No output file is ever created, and the timer keeps counting up indefinitely. I can manually encode the files using ffmpeg without issue.

I can crf-search the problematic files just fine, but the full encode doesn't work and doesn't generate any errors, it just gets stuck somehow.

**Comment by alexheretic** [comment]
`encode` is mostly a wrapper of an ffmpeg invocation. Can you see in your task manager the cmdline of the ffmpeg call. Try calling that manually and see if ffmpeg is waiting for some reason?

**Comment by darkstego** [comment]
The error was due to `-map 0`. It causes the following error:

> [mp4 @ 0x560f73476040] You requested a copy of the original timecode track so timecode metadata are now ignored
> [mp4 @ 0x560f73476040] Could not find tag for codec none in stream #2, codec not currently supported in container
> Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
> Error initializing output stream 0:0 -- 
> Svt[error]: deinit called without sending EOS!

and subsequently ffmpeg freezes. My guess is the default stream selection in ffmpeg did some error checking that seems to be skipped when explicitly selecting the streams.

**Comment by alexheretic** [comment]
Yeah seems ffmpeg should fail here, at the very least. Let me know if there are any issues with the args we're using. The `-map 0` is necessary in general to include all streams in the output.

**Comment by darkstego** [comment]
The error seems to arise due to timecode streams. It seems Apple supports MOV Quicktime timecode streams in mp4 containers, while most don't. ffmpeg gives an error when you try to copy a timecode stream to an mp4 file. This error crashes most codecs, but svt actually hangs on such error instead of failing gracefully.

**Comment by alexheretic** [comment]
Ah right, thanks for explanation 👍

**Comment by darkstego** [comment]
Just updating in case anyone else runs into the same issue of data streams freezing the encoding, you can pass the argument `--enc map=-0:d?` which will cause data streams to be ignored.
