### ISSUE TITLE
rav1e support

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#124]
I was trying to use ab-av1 auto-encode with rav1e for efficiency comparison purposes and noticed that changes would be required for this to work correctly.

* rav1e doesn't support CRF as yet, it only supports QP. The -crf switch doesn't fail when used from within FFmpeg though, it just results in a warning and the encoder using its default -qp value, which is 100. So no matter how many CRF values ab-av1 tries, the encoding result is always the same.
* rav1e's quantizer range is 0 to 255, but the default --max-crf in ab-av1 seems to be 55. This was actually the first issue I discovered, since the CRF chosen by ab-av1 always ended up as 55.
* the speed is controlled with `-speed` instead of `-preset`, and due to the warning-and-defaulting behavior similar to above, the default speed setting of 6 is always used.

Example of a command I tried and which runs, but has the above issues:

>ab-av1 auto-encode -e librav1e --keyint 99999 --min-vmaf 93.4 --pix-format yuv420p --preset 3 --vmaf n_threads=4 --enc tiles=4 --thorough --input 1.mp4 -o 1.rav1e.s3.mp4

(`--thorough` should work quite well with rav1e, probably the best of all the software AV1 encoders, due to the high granularity of its QP range. Which is one reason I'm interested in using rav1e with ab-av1.)

In case anyone's wondering why rav1e is only using a single thread by default, rav1e only supports tile threading currently, and you need to set the number of tiles yourself using `-tiles`. Every tile is processed in its own thread, so the more tiles, the more parallelization. But tiles also decrease compression efficiency, so keep that in mind.

Thanks for this tool btw. I've mostly been using it with SVT-AV1 so far.

**Comment by alexheretic** [comment]
Thanks for raising this, it makes sense to get rav1e working as much as it can. 

We can configure it to use `-qp` like vaapi encoders do. We also have similar per-encoder settings for min/max crf & preset equivalents used elsewhere, so it should be easy enough to support librav1e.
