### ISSUE TITLE
Question about -svtav1-params tune=0

### ISSUE THREAD

**Issue by mr44er** [alexheretic/ab-av1#127]
Is this used as default? It is the parameter for aiming at visual quality on svtav1.

`vt[info]: SVT [config]: preset / tune / pred struct                                    : 5 / VQ / random access`

Just asking, because I used `--svt tune=0` explicit so far.

**Comment by alexheretic** [comment]
I am interested in better defaults. It's just that in my initial testing tune=0 vs tune=1 didn't convince me this was a worthwhile one to change. I guess when I don't see a clear improvement I tend to stick to upstream defaults.

It would be interesting to see further testing with vmaf/size/speed diffs with this param. Are you seeing notable differences?

**Comment by mr44er** [comment]
Modern codecs (with enough bitrate) are so mature, that I can't really tell the difference anymore, BUT:
It may look stupid to convert mostly 8bit material to 10bit (yuv420p10le-example). The encoding needs more time, but the output is always smaller and it avoids the banding-effect. Not always visible (normal people will never notice or what to look after) for me, not really important, but it's in any case the better option and never harmful.

Same goes for `tune=0` (or maybe I'm thinking wrong). I don't really see a difference with my eyes, but I know if it is not set, it aims at PSNR. I think this is counterproductive when aiming at VMAF in the first place.

**Comment by alexheretic** [comment]
I guess I have a slightly different policy. Though I'm similarly interested in best practices and advice I read, I don't tend to use them unless I can demonstrate some objective improvement from doing so, generally vmaf, size, speed.

So, for example, iirc I tried yuv420p vs yuv420p10le and saw vmaf improvements without much affect on size & speed. Hence av1 defaults to this pixel format.

It might be the same story with `tune=0`, perhaps it didn't surface well in my initial testing (which was more exploratory than exhaustive). I'll try running it through my test suite of videos and seeing if there's a compelling diff. (And I do appreciate issues like this which can help find potentially better settings).

The advantage of _not_ overriding upstream defaults is upstream can improve without changes here. Not a huge deal, but if there's not much different either way I think it makes sense to stick with upstream.

**Comment by mr44er** [comment]
I also don't fiddle with every single knob (before checking out VMAF my sweet spot was just -crf 28 -preset 5/slower for everything on av1 and hevc), but I stumbled over this just because of this PSNR vs. VMAF thingie. Maybe upstream hasn't changed yet because PSNR is still the better known term for companies, instead of VMAF. I can't tell the real substantial difference, looking forward to your testing.

**Comment by alexheretic** [comment]
I ran some tune=0 vs tune=1 tests. I would say the overall result is inconclusive.

There are some results where `tune=0` is a little better, some a little worse, some where it just produces slightly higher quality but with slightly higher size.

There's no compelling evidence to change the default or prevent changing the default. Perhaps if we compare more videos this will change?

<details>

<summary>Results</summary>

_Tests running `ab-av1 crf-search -i $v --preset 6` vs `ab-av1 crf-search -i $v --preset 6 --svt tune=0`._

### 4kmedia-sony-new-york-fashion-demo.mp4

```
 -> tune=1
- crf 32 VMAF 94.59 (16%)
- crf 21 VMAF 97.85 (47%)
  00:12:49 crf 31 VMAF 95.03 predicted video stream size 163.21 MiB (17%) taking 15 minutes

 -> tune=0
- crf 32 VMAF 94.73 (15%)
- crf 21 VMAF 98.04 (47%)
  00:13:15 crf 31 VMAF 95.18 predicted video stream size 158.88 MiB (17%) taking 15 minutes
```

### 4kmedia-spacex-launch-demo.mp4

```
 -> tune=1
- crf 32 VMAF 96.69 (9%)
- crf 43 VMAF 94.41 (4%)
  00:04:25 crf 40 VMAF 95.11 predicted video stream size 8.51 MiB (5%) taking 5 minutes

 -> tune=0
- crf 32 VMAF 96.77 (9%)
- crf 43 VMAF 94.46 (4%)
  00:04:27 crf 40 VMAF 95.15 predicted video stream size 8.73 MiB (5%) taking 5 minutes
```

### pixabay-bridge-23544.mp4

```
 -> tune=1
- crf 32 VMAF 97.71 (33%)
- crf 43 VMAF 94.85 (16%)
  00:06:11 crf 42 VMAF 95.16 predicted video stream size 16.45 MiB (17%) taking 2 minutes

 -> tune=0
- crf 32 VMAF 97.55 (35%)
- crf 43 VMAF 94.53 (17%)
  00:06:16 crf 41 VMAF 95.15 predicted video stream size 19.04 MiB (19%) taking 2 minutes
```

### pixabay-elevator-3735.mp4

```
 -> tune=1
- crf 32 VMAF 97.43 (67%)
- crf 43 VMAF 95.90 (34%)
- crf 55 VMAF 92.33 (15%)
  00:01:41 crf 46 VMAF 95.21 predicted video stream size 5.54 MiB (27%) taking 36 seconds

 -> tune=0
- crf 32 VMAF 97.48 (71%)
- crf 43 VMAF 95.96 (36%)
- crf 55 VMAF 92.38 (16%)
  00:01:40 crf 46 VMAF 95.27 predicted video stream size 5.93 MiB (29%) taking 36 seconds
```

### pixabay-lemon-82602.mp4

```
 -> tune=1
- crf 32 VMAF 95.46 (21%)
- crf 43 VMAF 91.93 (11%)
  00:04:17 crf 33 VMAF 95.22 predicted video stream size 17.96 MiB (20%) taking 2 minutes

 -> tune=0
- crf 32 VMAF 95.48 (22%)
- crf 43 VMAF 91.92 (11%)
  00:04:21 crf 33 VMAF 95.24 predicted video stream size 18.72 MiB (21%) taking 2 minutes
```

### pixabay-nature-31377.mp4

```
 -> tune=1
- crf 32 VMAF 98.46 (209%)
- crf 43 VMAF 91.17 (104%)
  00:08:33 Error: Failed to find a suitable crf

 -> tune=0
- crf 32 VMAF 98.73 (214%)
- crf 43 VMAF 91.45 (107%)
  00:08:34 Error: Failed to find a suitable crf
```

### pixabay-sunrise-83880.mp4

```
 -> tune=1
- crf 32 VMAF 96.47 (83%)
- crf 43 VMAF 95.46 (35%)
- crf 55 VMAF 92.80 (14%)
  00:05:38 crf 45 VMAF 95.18 predicted video stream size 2.72 MiB (30%) taking 71 seconds

 -> tune=0
- crf 32 VMAF 96.60 (100%)
- crf 43 VMAF 95.72 (44%)
- crf 55 VMAF 92.95 (16%)
  00:05:34 crf 46 VMAF 95.24 predicted video stream size 3.12 MiB (34%) taking 69 seconds
```

### pixabay-turntable-8453.mp4

```
 -> tune=1
- crf 32 VMAF 94.26 (12%)
- crf 21 VMAF 95.65 (28%)
  00:01:14 crf 26 VMAF 95.13 predicted video stream size 2.91 MiB (19%) taking 38 seconds

 -> tune=0
- crf 32 VMAF 94.30 (12%)
- crf 21 VMAF 95.67 (29%)
  00:01:16 crf 26 VMAF 95.14 predicted video stream size 3.02 MiB (20%) taking 40 seconds
```


</details>

**Comment by mr44er** [comment]
Mhm, I see it this way: without in-depth look in 15/18 cases it gives better VMAF and file size aside, that's likely the price to pay for better quality around all moving things. I remember my first steps on HEVC, medium gave me already good quality and I thought the slower presets will only do more effort keeping the file small. But that isn't true, mostly the area around moving things is much more smoother and with the slower presets comes also slightly more file size. Not much, not always.

This bridge video is problematic in two ways:
difficult to compress, camera flying means nearly every pixel is moving and the cables of the bridge have that well-known distortion effect (how is it called?).
I think if done right (maybe another filter or lens before everything?) could rule that out. Shame that the video is already compressed and the distortion is also on the 2160p-version.
Maybe this irritates VMAF, I don't know.

I picked the bridge video from here https://pixabay.com/de/videos/br%C3%BCcke-terminal-architektur-23544/ in all four resolutions, renamed then accordingly and here my tests:

<details><summary>tune1 preset8</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 
- crf 32 VMAF 92.23 (57%)
- crf 21 VMAF 94.83 (119%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-1080.mp4
- crf 32 VMAF 94.31 (50%)
- crf 21 VMAF 96.06 (105%)
crf 28 VMAF 95.04 predicted video stream size 13.74 MiB (65%) taking 52 seconds

ab-av1 crf-search -i brucke-23544-1440.mp4 
- crf 32 VMAF 94.56 (33%)
- crf 21 VMAF 96.37 (71%)
crf 29 VMAF 95.13 predicted video stream size 17.48 MiB (40%) taking 50 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 
- crf 32 VMAF 97.20 (29%)
- crf 43 VMAF 94.53 (14%)
crf 41 VMAF 95.09 predicted video stream size 15.83 MiB (16%) taking 2 minutes
```

</p>
</details> 
<details><summary>tune0 preset8</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 --svt tune=0
- crf 32 VMAF 91.82 (61%)
- crf 21 VMAF 94.81 (126%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-1080.mp4 --svt tune=0
- crf 32 VMAF 93.89 (54%)
- crf 21 VMAF 95.90 (110%)
- crf 26 VMAF 95.12 (80%)
- crf 27 VMAF 94.92 (75%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-1440.mp4 --svt tune=0
- crf 32 VMAF 94.01 (35%)
- crf 21 VMAF 96.12 (75%)
crf 27 VMAF 95.08 predicted video stream size 21.60 MiB (50%) taking 47 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --svt tune=0
- crf 32 VMAF 97.00 (31%)
- crf 43 VMAF 94.07 (15%)
- crf 40 VMAF 94.98 (18%)
crf 39 VMAF 95.26 predicted video stream size 19.44 MiB (20%) taking 2 minutes

```
</p>
</details> 
<details><summary>tune1 preset5</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 --preset 5
- crf 32 VMAF 94.40 (60%)
- crf 21 VMAF 96.08 (110%)
crf 28 VMAF 95.12 predicted video stream size 7.88 MiB (75%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-1080.mp4 --preset 5
- crf 32 VMAF 95.85 (52%)
- crf 43 VMAF 93.68 (27%)
crf 36 VMAF 95.22 predicted video stream size 8.64 MiB (41%) taking 4 minutes

ab-av1 crf-search -i brucke-23544-1440.mp4 --preset 5
- crf 32 VMAF 95.87 (35%)
- crf 43 VMAF 93.62 (18%)
crf 36 VMAF 95.18 predicted video stream size 11.81 MiB (27%) taking 5 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --preset 5
- crf 32 VMAF 98.27 (31%)
- crf 43 VMAF 96.21 (14%)
- crf 55 VMAF 92.35 (7%)
crf 47 VMAF 95.19 predicted video stream size 11.28 MiB (11%) taking 10 minutes
```

</p>
</details> 
<details><summary>tune0 preset5</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 --svt tune=0 --preset 5
- crf 32 VMAF 94.14 (66%)
- crf 21 VMAF 96.11 (118%)
- crf 27 VMAF 95.21 (87%)
- crf 28 VMAF 95.01 (82%)
- crf 29 VMAF 94.80 (78%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-1080.mp4 --svt tune=0 --preset 5
- crf 32 VMAF 95.46 (58%)
- crf 43 VMAF 92.86 (29%)
crf 34 VMAF 95.09 predicted video stream size 10.80 MiB (51%) taking 4 minutes

ab-av1 crf-search -i brucke-23544-1440.mp4 --svt tune=0 --preset 5
- crf 32 VMAF 95.43 (39%)
- crf 43 VMAF 92.84 (20%)
crf 34 VMAF 95.06 predicted video stream size 14.94 MiB (34%) taking 5 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --svt tune=0 --preset 5
- crf 32 VMAF 98.14 (34%)
- crf 43 VMAF 95.86 (16%)
- crf 55 VMAF 91.78 (8%)
crf 46 VMAF 95.07 predicted video stream size 12.98 MiB (13%) taking 11 minutes
```

</p>
</details> 
<details><summary>tune0 enable-overlays1 preset5</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 --svt tune=0 --svt enable-overlays=1 --preset 5
- crf 32 VMAF 94.14 (67%)
- crf 21 VMAF 96.13 (121%)
- crf 27 VMAF 95.22 (89%)
- crf 28 VMAF 95.00 (84%)
- crf 29 VMAF 94.82 (80%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-1080.mp4 --svt tune=0 --svt enable-overlays=1 --preset 5
- crf 32 VMAF 95.45 (59%)
- crf 43 VMAF 92.82 (30%)
crf 34 VMAF 95.07 predicted video stream size 11.04 MiB (52%) taking 4 minutes

ab-av1 crf-search -i brucke-23544-1440.mp4 --svt tune=0 --svt enable-overlays=1 --preset 5
- crf 32 VMAF 95.44 (40%)
- crf 43 VMAF 92.78 (20%)
crf 34 VMAF 95.05 predicted video stream size 15.36 MiB (35%) taking 6 minutes

No 2160p tested here, seems senseless.
```

</p>
</details> 

Test with filters:
https://matplotlib.org/mpl_examples/images_contours_and_fields/interpolation_methods.hires.png
<details><summary>bicubic, lanczos</summary>
<p>

```
ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:718:flags=bicubic"
- crf 32 VMAF 92.15 (51%)
- crf 21 VMAF 94.54 (105%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:722:flags=bicubic"
- crf 32 VMAF 92.30 (52%)
- crf 21 VMAF 94.64 (106%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:718:flags=lanczos"
- crf 32 VMAF 92.21 (55%)
- crf 21 VMAF 94.53 (113%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:722:flags=lanczos"
- crf 32 VMAF 92.31 (56%)
- crf 21 VMAF 94.62 (114%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=bicubic"
- crf 32 VMAF 94.21 (86%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=lanczos"
- crf 32 VMAF 94.36 (90%)
Error: Failed to find a suitable crf
```

</p>
</details> 
<details><summary>bicubic, lanczos, tune0, upscale 1080p preset5</summary>
<p>

```

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:718:flags=bicubic" --svt tune=0
- crf 32 VMAF 91.65 (55%)
- crf 21 VMAF 94.33 (111%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:722:flags=bicubic" --svt tune=0
- crf 32 VMAF 91.81 (56%)
- crf 21 VMAF 94.44 (113%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:718:flags=lanczos" --svt tune=0
- crf 32 VMAF 91.64 (59%)
- crf 21 VMAF 94.35 (120%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:722:flags=lanczos" --svt tune=0
- crf 32 VMAF 91.82 (60%)
- crf 21 VMAF 94.45 (121%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=bicubic" --svt tune=0
- crf 32 VMAF 94.11 (90%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=lanczos" --svt tune=0
- crf 32 VMAF 94.22 (94%)
Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=bicubic" --svt tune=0 --preset 5
- crf 32 VMAF 95.10 (96%)
- crf 43 VMAF 92.66 (49%)
- crf 33 VMAF 94.93 (91%)

Error: Failed to find a suitable crf

ab-av1 crf-search -i brucke-23544-720.mp4 --vfilter "scale=-1:1080:flags=lanczos" --svt tune=0 --preset 5
- crf 32 VMAF 95.19 (101%)
- crf 43 VMAF 92.69 (51%)
- crf 33 VMAF 95.02 (95%)
- crf 34 VMAF 94.84 (89%)
Error: Failed to find a suitable crf
```

</p>
</details> 
<details><summary>downscale 2160p to 720p+filters bicubic, lanczos</summary>
<p>


```
ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=bicubic" --preset 5
crf 32 VMAF 95.04 predicted video stream size 6.48 MiB (7%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=lanczos" --preset 5
- crf 32 VMAF 94.99 (7%)
- crf 21 VMAF 96.67 (13%)
crf 31 VMAF 95.18 predicted video stream size 7.33 MiB (7%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=bicubic" --preset 5 --svt tune=0
- crf 32 VMAF 94.95 (7%)
- crf 21 VMAF 96.83 (12%)
crf 31 VMAF 95.19 predicted video stream size 7.30 MiB (7%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=lanczos" --preset 5 --svt tune=0
- crf 32 VMAF 94.98 (7%)
- crf 21 VMAF 96.89 (13%)
crf 31 VMAF 95.22 predicted video stream size 7.76 MiB (8%) taking 2 minutes
```

</p>
</details> 

And here is the first positive result, those problematic bridge cables seem to work best with spline.
<details><summary>downscale 2160p to 720p+filters gauss, spline</summary>
<p>


```
ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=gauss" --preset 5 
- crf 32 VMAF 95.21 (5%)
- crf 43 VMAF 92.00 (3%)
crf 33 VMAF 95.02 predicted video stream size 4.51 MiB (5%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 5
- crf 32 VMAF 94.95 (7%)
- crf 21 VMAF 96.66 (12%)
crf 31 VMAF 95.14 predicted video stream size 7.18 MiB (7%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=gauss" --preset 5 --svt tune=0
- crf 32 VMAF 95.15 (5%)
- crf 43 VMAF 91.52 (3%)
- crf 33 VMAF 94.91 (5%)
crf 32 VMAF 95.15 predicted video stream size 5.08 MiB (5%) taking 2 minutes

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 5 --svt tune=0
- crf 32 VMAF 94.98 (7%)
- crf 21 VMAF 96.87 (13%)
crf 31 VMAF 95.21 predicted video stream size 7.62 MiB (8%) taking 2 minutes
```


</p>
</details> 
<details><summary>Another round with preset8-6 (No luck, same results)</summary>
<p>


```
ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline"
- crf 32 VMAF 92.40 (7%)
- crf 21 VMAF 94.94 (14%)
- crf 10 VMAF 97.14 (35%)
crf 20 VMAF 95.09 predicted video stream size 14.68 MiB (15%) taking 31 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 7
- crf 32 VMAF 92.97 (7%)
- crf 21 VMAF 95.74 (13%)
crf 24 VMAF 95.25 predicted video stream size 11.20 MiB (11%) taking 45 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 6
- crf 32 VMAF 94.64 (7%)
- crf 21 VMAF 96.40 (13%)
crf 30 VMAF 95.05 predicted video stream size 7.93 MiB (8%) taking 58 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --svt tune=0
- crf 32 VMAF 92.13 (7%)
- crf 21 VMAF 94.80 (15%)
- crf 10 VMAF 97.03 (36%)
- crf 20 VMAF 94.94 (15%)
crf 19 VMAF 95.11 predicted video stream size 16.11 MiB (16%) taking 34 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 7 --svt tune=0
- crf 32 VMAF 92.68 (7%)
- crf 21 VMAF 95.86 (14%)
crf 24 VMAF 95.31 predicted video stream size 11.55 MiB (12%) taking 48 seconds

ab-av1 crf-search -i brucke-23544-2160.mp4 --vfilter "scale=-1:720:flags=spline" --preset 6 --svt tune=0
- crf 32 VMAF 94.58 (8%)
- crf 21 VMAF 96.61 (13%)
crf 30 VMAF 95.06 predicted video stream size 8.40 MiB (8%) taking 68 seconds
```


</p>
</details> 

Now some other experiment. I grabbed the 1080p https://pixabay.com/de/videos/aufzug-das-einkaufszentrum-gold-3735/, the 2160p https://pixabay.com/de/videos/natur-wellen-ozean-meer-felsen-31377/
and cut off the first 10 seconds from all three. I forced 1080p/25fps to have same settings/properties from beginning, also lossless output.

```
ffmpeg -i aufzug-3735-1080.mp4 -to 0:10 -vf scale=1920:1080 -r 25 -codec ffv1 -an -sn -dn vida.mkv
ffmpeg -i brucke-23544-2160.mp4 -to 0:10 -vf scale=1920:1080 -r 25 -codec ffv1 -an -sn -dn vidb.mkv
ffmpeg -i natur-31377-2160.mp4 -to 0:10 -vf scale=1920:1080 -r 25 -codec ffv1 -an -sn -dn vidc.mkv
```

Now copying this wonderful abomination together:
`ffmpeg -i vida.mkv -i vidb.mkv -i vidc.mkv -filter_complex "[0:v:0][1:v:0][2:v:0]concat=n=3:v=1[outv]" -map "[outv]" -vcodec ffv1 triplevid.mkv`

Here I expected a better result with tune=0, because of the 2:1 ratio of 'good' clip at the beginning/end and with 'bad' in between. But it wasn't enough:

```
ab-av1 crf-search -i triplevid.mkv --preset 5
- crf 32 VMAF 95.90 (4%)
- crf 43 VMAF 92.06 (2%)
crf 35 VMAF 95.11 predicted video stream size 21.32 MiB (3%) taking 4 minutes

ab-av1 crf-search -i triplevid.mkv --preset 5 --svt tune=0
- crf 32 VMAF 95.74 (4%)
- crf 43 VMAF 91.68 (2%)
crf 34 VMAF 95.19 predicted video stream size 23.57 MiB (3%) taking 4 minutes
```

It would be interesting to play with the uncompressed source, but back to the main question I think if you have such a ~30sec scene in a 90minute-video, tune=0 should throw out statistically always the better VMAF.

**Comment by mr44er** [comment]
Just noticed they use and explain it (but not why it's not default) for example 2 and 3: https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Ffmpeg.md

**Comment by alexheretic** [comment]
iirc I wasn't convinced it made sense to change the default from the upstream, rather upstream should be convinced.

Maybe we should have another discussion about config, like an ab-av1 config file or env vars for easier setting of user overrides. If you're interested in that open an issue.

**Comment by mr44er** [comment]
That is ok and in the meantime obsolete for me, because svt-av1-psy uses more of those "better" defaults which also could not convince upstream. tune3 is not their default, but has won my heart (and even better than my previous fav tune0). :)

**Comment by iPaulis** [comment]
Hey @mr44er, maybe a bit off topic, but what do you like so much about tune3? I don't have much experience with different tunes, only that I perceptually liked tune0 over default when I tested it a couple of years ago, what is the main difference with tune3?

**Comment by mr44er** [comment]
It was a recommendation from -psy devs, if one would like tune0 then he would like tune3 more and that teased me. I could see differences in zoomed frame-by-frame differences, but both just looked good. In crf-search comparisons tune3 mostly wins, so...easy decision. :)
