### ISSUE TITLE
Information about ab-av1

### ISSUE THREAD

**Issue by manbug10** [alexheretic/ab-av1#138]
I have a question, can this application be used to convert videos without problems or is it only for testing or development?

**Comment by alexheretic** [comment]
_ab-av1_ is built on top of ffmpeg, the individual encoders & vmaf. I don't believe any of these are "without problems", but I also don't think _ab-av1_ itself is particularly adding any.

**Comment by manbug10** [comment]
So if it can be used for daily use? to convert videos?

**Comment by alexheretic** [comment]
This project has no known issues itself that should prevent regular use. So yes.

Or as much as you consider ffmpeg, vmaf & svt-av1 (or whatever else encoder) ready for daily use.

**Comment by manbug10** [comment]
Thank you very much friend, I will start using it since I have seen that your project is quite good.
