### ISSUE TITLE
VMAF calculation issue with recent FFmpeg git

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#142]
I'm having an issue with extremely low (~1) VMAF scores when using an FFmpeg built from recent git code. The score is always this low with any CRF, and ab-av1 keeps going lower and lower until the size of `max-encoded-percent` is reached and it exits.

I've tracked the issue down to the following FFmpeg commit: https://github.com/FFmpeg/FFmpeg/commit/c94e9d03b44d21282418dfb6c84f4f7942d4db03

Calculating VMAF normally using FFmpeg still works fine.

**Comment by veikk0** [comment]
Looking through the ab-av1 repository, I can't really find a reason why VMAF calculation is done with pipes instead of a single FFmpeg command.

If the reason is pixel format conversion, then the [format](https://ffmpeg.org/ffmpeg-filters.html#format-1) filter is the way to go. I believe `-pix_fmt` is an alias for the format filter anyway and more of a legacy option, but it's more convenient when typing a command for a simple encode.

**Comment by alexheretic** [comment]
Yep pixel format & vfilter. It may be worth trying to crunch it into a single call. I'd need to regression test such a change.

**Comment by alexheretic** [comment]
#177 changes vmaf to a single ffmpeg call. In my testing this produces identical results to previous code though much simpler and easier to reproduce in a manual ffmpeg call.

**Comment by veikk0** [comment]
Nice! I'll do some before-after testing too and report back.

**Comment by veikk0** [comment]
#WorksForMe
