### ISSUE TITLE
VMAF scores for HEVC encoding via VA-API unexpectedly low

### ISSUE THREAD

**Issue by lynix** [alexheretic/ab-av1#143]
When trying to find a CRF (or QP in this case) for VA-API accelerated HEVC encoding (following [this post](https://alexheretic.github.io/posts/ab-av1-2/#va-api)) I get unexpectedly bad VMAF scores making ab-av1 giving up on it:

```
$ ab-av1 crf-search -e hevc_vaapi -i sample.mkv --enc-input hwaccel=vaapi --enc-input hwaccel_output_format=vaapi
- crf 32 VMAF 69.75 (4%)
- crf 21 VMAF 80.09 (29%)
- crf 10 VMAF 81.60 (143%)
  00:04:25 ########################################################################### (sampling crf 10, eta 0s)
Error: Failed to find a suitable crf
```

If I encode the sample by hand and let ab-av1 determine its VMAF score afterwards it gets rated much better:

```
$ ffmpeg \
    -vaapi_device /dev/dri/renderD128 \
    -i sample.mkv \
    -vf 'format=nv12,hwupload' \
    -c:v hevc_vaapi \
    -profile:v main \
    -rc_mode CQP \
    -qp 21 \
    sample-cqp21.mkv
```

```
$ ab-av1 vmaf --reference sample.mkv --distorted sample-cqp21.mkv
96.17253
```

So my guess would be that my manual encode uses different `ffmpeg` options compared to what ab-av1 does. I tried adding some of my options (e.g. the vfilter) but that made `ffmpeg` fail due to incompatible arguments.

**Comment by alexheretic** [comment]
Possibly related to the 20s samples of sample.mkv that are encoded and tested during the crf-search. How long is sample.mkv?

You can do an equivalent full encode for the crf-search by using a high number of samples (longer than the total duration) e.g. `--samples 999`.

It's possible the sample(s) picked by default are just a bad fit for this video, or something went wrong creating the samples or encoding them.

**Comment by lynix** [comment]
I realize I have used the term 'sample' in a misleading way in my original post, sorry for that!

'sample.mkv' is the actual movie which is 1h 58min long. Should have called it 'example' or 'input'.

So I've tried 5 other video files to see whether it's bad luck with sample alignment but they all seem to get really bad VMAF scores when run through `crf-search` compared to manual encoding.

I've also tried taking samples (this time I really mean _samples_ i.e. short portions of the input files) to avoid mis-aligned frames between original and distorted input during VMAF rating but this didn't change anything either.

I'll try to capture the exact arguments ab-av1 is using to call ffmpeg during encoding of its samples and see if I can spot anything that is significantly different to my manual approach.

**Comment by alexheretic** [comment]
Try `ab-av1 sample-encode -crf 21 --keep ...`  which will create the samples, encode them and not clean them up so you can manually see if there is an issue with the samples or encoded versions.

They'll be in a dir named something like `.ab-av1-xxxxxx`.

**Comment by veikk0** [comment]
Couple things come to mind:

* Does the issue also occur with other encoders, like libx264? If it's not limited to just one encoder and you're using a recent git build of FFmpeg, this could be due to  #142 
* If this is limited to a single encoder, try using `--enc fps_mode=passthrough`. This should eliminate the possibility of the encoder dropping frames it considers duplicates and causing a desync during VMAF calculation.

**Comment by lynix** [comment]
When giving `--enc fps_mode=passthrough` a try I realized that I'm no longer able to reproduce the issue.

I really don't get it since there has been no (relevant) package update (ffmpeg, libva, kernel) and I'm testing with the exact same files. Anyway, I'll close this one, sorry for the noise.
