### ISSUE TITLE
Please increase support for QSVEncC64?

### ISSUE THREAD

**Issue by henanzheng** [alexheretic/ab-av1#144]
QSVEncC64 is rigaya's work, widely supported, provides more parameters than ffmpeg's qsv, a very prominent place: hardware decoding + hardware encoding in the case of quality assurance, resolution 1080, three times faster than ffmpeg's qsv encoding and nvenc encoding, other resolutions are also much faster, worthy of support, simple encoding is as follows:

QSVEncC64.exe --avhw -i in.mp4 --avsync forcecfr -c hevc --icq 24 --profile main10 --output-depth 10 --quality best --vpp-detail-enhance 25 --sao none --audio-codec aac --audio-bitrate 96 -o out.mp4

Thank you

**Comment by henanzheng** [comment]
At 1080 resolution, HEVC transcoding speed can reach around 280fps, while FFMPEG's is usually around 100fps.

**Comment by henanzheng** [comment]
Forgot to mention, the graphics card is Intel's A380.

**Comment by henanzheng** [comment]
![1111](https://github.com/alexheretic/ab-av1/assets/111262981/cc461312-791d-444f-8141-82997a3449d9)

**Comment by alexheretic** [comment]
Hello, it's possible to support something other than ffmpeg but it is more difficult. An alternative investigation would be finding out why ffmepg is slower for this.

As I don't have any intel hardware this isn't something I can move forward myself.

**Comment by henanzheng** [comment]
Sorry for not replying in time.

The reason why QSVEnc hardware decoding + hardware encoding is faster, here may be a clue:

https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#options-for-frame-buffer

FFMPEG's hardware decoding scheme may be different and the documentation is not detailed.

Sorry to confuse you.

**Comment by mr44er** [comment]
I know nothing about QSV/Intel, but I remember from tests on Radeon VCE that decoding and encoding had to be specified to target the GPU. Otherwise only the encoding will be done in hardware, decoding with ffmpeg defaults to software and it will show "native".

Does this help?
`ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i $input -vf 'format=nv12|vaapi,hwupload' -c:v hevc_vaapi -qp 28 -sn outputqp28.mkv`

**Comment by alexheretic** [comment]
I'll close this since I can see no way forward myself. Please reopen with a clear course of action or further ideas.
