### ISSUE TITLE
ETA can become excessively high and cause an overflow

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#146]
I was encoding a file with SVT-AV1's preset 1 when ab-av1 crashed:

>⠄ Searching 00:06:00 ###############-------------------------------------------- (sampling crf 23, eta 580176947043y)thread 'main' panicked at 'overflow when adding durations', library/core/src/time.rs:920:31
>note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The ETA started climbing and eventually reached the very high number above. I assume this is because preset 1 is very slow, not very well threaded, and though clip I was encoding is only 60 frames long, it has quite a lot of detail. I also had other encodes going at the time.

The input file was a CRF 0 x264 transcode of touchdown_pass_1080p_60f.y4m from the objective-1-fast dataset available from [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz).

Command to reproduce:

>ab-av1 auto-encode -e libsvtav1 --svt tune=0 --keyint 600 --min-vmaf 92.8 --max-crf 63 --pix-format yuv420p --preset 1 --vmaf n_threads=16 --touchdown_pass_1080p_60f.mp4  --output output.mp4

I'm on Linux Mint 21.1 running ab-av1 0.7.7.

**Comment by alexheretic** [comment]
Thanks for raising this. I haven't managed to reproduce this, but I can see where it may have happened in the upstream progress-bar code.

**Comment by alexheretic** [comment]
I have managed to reproduce now & raised an issue upstream https://github.com/console-rs/indicatif/issues/561 I'll also try to look into a fix there when I get a moment.

**Comment by DuckDuckWhale** [comment]
I've also noticed on the newest commit that the ETA rises for a while until it becomes excessively high, then falls back down to a sensible value, and cycles until it's done. There's gotta be enough information to deduce that it shouldn't be a week until a two-hour encode is done.

**Comment by alexheretic** [comment]
The overflow should be fixed now, the very high eta issues upstream remain, see
* https://github.com/console-rs/indicatif/issues/556
* https://github.com/console-rs/indicatif/issues/580

**Comment by alexheretic** [comment]
#174 is probably the quickest way to fix ETAs, unless upstream ever get round to improving it. I think we can close this issue now the immediate actions have been taken.
