### ISSUE TITLE
cache error: Read corrupted data at file offset None backtrace ()

### ISSUE THREAD

**Issue by mr44er** [alexheretic/ab-av1#148]
Getting this warning during search scan, but the encode runs fine:
`
⠲ Searching 00:05:26 ####--------------------------------------------------------------------------------------------------- (sampling crf 32, eta 30m)cache error: Read corrupted data at file offset None backtrace ()
⠤ Searching 00:10:13 #######------------------------------------------------------------------------------------------------ (sampling crf 32, eta 29m)cache error: Read corrupted data at file offset None backtrace ()
⠖ Searching 00:14:40 ##########--------------------------------------------------------------------------------------------- (sampling crf 32, eta 37m)cache error: Read corrupted data at file offset None backtrace ()
⠲ Searching 00:21:05 #############------------------------------------------------------------------------------------------ (sampling crf 32, eta 28m)cache error: Read corrupted data at file offset None backtrace ()
⠒ Searching 00:25:41 #################-------------------------------------------------------------------------------------- (sampling crf 32, eta 25m)cache error: Read corrupted data at file offset None backtrace ()
⠙ Searching 00:31:23 ####################----------------------------------------------------------------------------------- (sampling crf 32, eta 25m)cache error: Read corrupted data at file offset None backtrace ()
⠤ Searching 00:35:26 #######################-------------------------------------------------------------------------------- (sampling crf 32, eta 33m)cache error: Read corrupted data at file offset None backtrace ()
⠋ Searching 00:40:03 ##########################----------------------------------------------------------------------------- (sampling crf 21, eta 23m)cache error: Read corrupted data at file offset None backtrace ()
⠲ Searching 00:46:33 #############################-------------------------------------------------------------------------- (sampling crf 21, eta 22m)cache error: Read corrupted data at file offset None backtrace ()
⠒ Searching 00:52:01 #################################---------------------------------------------------------------------- (sampling crf 21, eta 21m)cache error: Read corrupted data at file offset None backtrace ()
`

Any quick idea? I just updated my ports, I guess this comes from rust?
If not, pls ignore me...FreeBSD :)

**Comment by alexheretic** [comment]
looks like the sample-encode cache has become corrupted. I think the warning output isn't playing nicely with the progress bar.

You can "fix" by deleting the cache usually in .cache/ab-av1.

**Comment by mr44er** [comment]
Thx, that worked! :+1:
