### ISSUE TITLE
How to init a hardware device

### ISSUE THREAD

**Issue by zachron** [alexheretic/ab-av1#157]
Hello,

I am trying to pass to ffmpeg to init a hardware device, via the `-init_hw_device`  ffmpeg option. I would think this would be done with the the `--enc-input` but it just thinks i am trying to use the -i option in there.  It looks like in the source it just checks to see if it starts with a -i, which if trying to filter out file input that would work, but if trying to do this, it breaks it.  Is there a different way to do this, or a possible fix?

Thanks!

**Comment by alexheretic** [comment]
Yep you are correct, the 'starts with "-i"' validation is causing this issue and is in fact unnecessary anyway. Will remove.
