### ISSUE TITLE
Enhancement: Print scanning results in auto-encode mode

### ISSUE THREAD

**Issue by t-nil** [alexheretic/ab-av1#158]
If `auto-encode` could print the VMAF results per CRF, as does crf-search, that would be useful IMO to track the progress and identify outliers.

**Comment by alexheretic** [comment]
Yes I think it would make sense to be able to opt into the crf-search output when running auto-encode.

**Comment by alexheretic** [comment]
Logging (e.g. `RUST_LOG=ab_av1=info`) was added in https://github.com/alexheretic/ab-av1/blob/main/CHANGELOG.md#v0715

It is currently mostly meant for non-terminal use cases or debugging. But it also serves as a verbose output.

**Comment by t-nil** [comment]
Wonderful, thanks!
