### ISSUE TITLE
Select temporal pooling of VMAF score

### ISSUE THREAD

**Issue by t-nil** [alexheretic/ab-av1#161]
Appearently, libvmaf still pools/aggregates the VMAF scores of individual frames by mean. [^1] Options for minimum and harmonic mean exist, which lean towards lower scores, and as such are less forgiving when there are small parts of a video with lower VMAF score. [^2][^3][^6] This should be settable by adding `pool=harmonic_mean` or `pool=min` to the libvmaf vfilter parameters.[^1][^4][^5]

---

A quick test showed no error while sampling, and suggests that the VMAF score (`--preset 6` on AV1) has lowered slightly, which seems plausible, as there is a higher CRF needed to reach a quality level with 'better worst frames'. I currently don't have enough energy to test this further, but maybe adding an extra flag would be worth it. What do you think?

Weirdly enough, the flag isn't displayed in FFmpeg filters docpage. I opened an issue https://trac.ffmpeg.org/ticket/10693

Also beware of https://github.com/Netflix/vmaf/issues/339 (but that hopefully isn't as relevant with high quality encoding settings)

```patch
diff --git a/src/command/args/vmaf.rs b/src/command/args/vmaf.rs
index f47b387..2d6e31d 100644
--- a/src/command/args/vmaf.rs
+++ b/src/command/args/vmaf.rs
@@ -48,7 +48,7 @@ impl Vmaf {
             );
         }
         let mut lavfi = args.join(":");
-        lavfi.insert_str(0, "libvmaf=");
+        lavfi.insert_str(0, "libvmaf=pool=harmonic_mean:");
 
         let mut model = VmafModel::from_args(&args);
         if let (None, Some((w, h))) = (model, distorted_res) {
```

[^1]: https://ffmpeg.org/doxygen/trunk/vf__libvmaf_8c_source.html#l00556
[^2]: https://netflixtechblog.com/toward-a-practical-perceptual-video-quality-metric-653f208b9652 *see Temporal Pooling*
[^3]: https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12 *see Temporal pooling*
[^4]: https://ffmpeg.org/doxygen/trunk/vf__libvmaf_8c.html#a9c1205b8a79bda0ef63cfb16bf09a1e2
[^5]: https://ffmpeg.org/doxygen/trunk/vf__libvmaf_8c.html#a0844c30604d852a8cab06774e45ea1cd
[^6]: https://github.com/Netflix/vmaf/blob/master/resource/doc/faq.md#q-why-the-aggregate-vmaf-score-sometimes-may-bias-easy-content-too-much-issue-20

EDIT: I now have done several tries, where harmonic_mean and mean produce the same scores. I have contacted the developers, maybe the feature is buggy.

**Comment by veikk0** [comment]
The fix was just committed to FFmpeg master: https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/5f4b7bf2b5b675a4a1dfc3b64c1c5dd03d80f278

**Comment by t-nil** [comment]
Closing because #164 seems better suited to investigate the issue
