### ISSUE TITLE
Release a Linux (statically linked) binary

### ISSUE THREAD

**Issue by devedse** [alexheretic/ab-av1#170]
Hello, I'm currently writing a script to include ab-av1 in a docker container (fileflows) to be able to automatically transcode my videos.

Installing it through cargo in a container without rust installed is a hassle though, so I was wondering if you could release a binary for Linux too?

**Comment by alexheretic** [comment]
Yeah should be easy to add a linux musl build on releases.

**Comment by alexheretic** [comment]
I also added a build manually to the latest release.

**Comment by devedse** [comment]
Thanks, will it be included automatically in new versions too?
