### ISSUE TITLE
Custom path for FFMPEG and FFPROBE

### ISSUE THREAD

**Issue by devedse** [alexheretic/ab-av1#172]
Hi, I'm currently working on integrating ab-av1 as a plugin for fileflows. However it seems the version of FFMPEG/FFPROBE that fileflows use doesn't seem to have support for VMAF.

Would it be possible to specify a custom path for FFMPEG/FFPROBE so that I can point the ab-av1 binary to a different ffmpeg then the one in the .env?

Devedse

**Comment by alexheretic** [comment]
It should be possible to setup a custom `PATH` env var for the ab-av1 process pointing to another ffmpeg.

**Comment by devedse** [comment]
Would that also work in Linux?

**Comment by alexheretic** [comment]
Yep this works fine for me, did you face any issues?
