### ISSUE TITLE
Bash Autocompletion Issue: Incorrect Handling of Spaces and Special Characters

### ISSUE THREAD

**Issue by a90091343** [alexheretic/ab-av1#180]
**Version Information**: Ubuntu 22.04.3 LTS; ab-av1 Version: v0.7.12; cargo Version: 1.75.0 (1d8b05cdd 2023-11-20)
**Installation Method**: Installed using 'cargo install ab-av1'
**Issue:**
I encountered a problem with the bash autocompletion feature in the ab-av1 software. I followed the recommended steps to enable autocompletion using the provided command:
`printf '. <(ab-av1 print-completions bash)\n' > ~/.local/share/bash-completion/completions/ab-av1`

**Steps to Reproduce:**
1. Have files with spaces and special characters, for example:
`'Dont.Look.Up.-(copy).mkv'  'Great details 8K AV1 HDR 60FPS (FUHD).mp4'`
2. Run the command `$ ab-av1 encode -i`.
3. Double-tab for autocompletion.

**Expected Behavior:**
The bash autocompletion should correctly handle spaces and special characters, displaying suggestions similar to:
`$ ls Great\ details\ 8K\ AV1\ HDR\ 60FPS\ \(FUHD\).mp4 `
or
`$ ls Dont.Look.Up.-\(copy\).mkv`

**Current Behavior:**
The autocompletion suggestions are displayed incorrectly, failing to handle spaces and special characters properly. Autocompletion suggestions appear as:
```
$ ab-av1 encode -i 
Dont.Look.Up.-(copy).mkv  details                   AV1                       60FPS                     
Great                     8K                        HDR                       (FUHD).mp4
```
**Additional Information:**
The issue makes it challenging to work with files containing spaces and special characters using ab-av1. Please consider addressing this autocompletion problem for a more user-friendly experience. Thank you!

**Comment by alexheretic** [comment]
Bash completions are generated using _clap_complete_ crate: I've raised an [issue upstream](https://github.com/clap-rs/clap/issues/5313).

**Comment by a90091343** [comment]
Thank you for your prompt response and for looking into the issue!
