### ISSUE TITLE
Much slower AV1 encode compared to directly calling ffmpeg or Handbrake

### ISSUE THREAD

**Issue by ViRb3** [alexheretic/ab-av1#183]
Hello,

I've been playing around with your tool today to compare x264 and svt-av1. I noticed that AV1 encoding was many times slower compared to the same encoding in ffmpeg directly or using Handbrake.

I'm running macOS 14.3 on Macbook Pro M3 Max and I have the latest ab-av1 (v0.7.13) from Cargo, and ffmpeg (6.1.1_2) + SvtAv1EncApp0 (1.8.0) from homebrew.

1. `ab-av1 crf-search -i input.mkv -e libx264 --preset veryslow`
   - estimates 2 minutes for `ab-av1 encode -e libx264 -i 'input.mkv' --crf 13.7 --preset veryslow`
   - actual encode takes 1:49 (very close)
   - `ffmpeg -i input.mkv -c:v libx264 -crf 13.7 -preset veryslow test.mkv` takes 1:49 (identical)
   - Handbrake with same CSRF = 14 and Preset = veryslow takes 1:45 (almost identical)

2. `ab-av1 crf-search -i input.mkv --preset 8`
   - estimates 3 minutes for `ab-av1 encode -i 'input.mkv' --crf 13 --preset 8`
   - actual encode takes 3:00 (identical)
   - `ffmpeg -i input.mkv -c:v libsvtav1 -crf 13 -preset 8  av1_test.mkv` takes 1:08 (almost 3 times faster)
   - Handbrake with same CSRF = 13 and Preset = 8 takes 0:41 (even faster)

Any ideas? Thanks!

**Comment by alexheretic** [comment]
Interesting, ab-av1 calls ffmpeg so there is no difference other than the args used.

Most likely the encode is taking longer as ab-av1 will default av1 encodes to yuv420p10le. This is/was advised with av1 to produce better quality output without any real increase in size.

Assuming your input is yuv420p try setting `--pix-format yuv420p` to get closer to default ffmpeg behaviour.

This makes me wonder about the general performance cost of `420p -> 420p10le` vs `420p -> 420p` & if the quality improvement is worthwhile for this to be default behaviour...

**Comment by ViRb3** [comment]
With `--pix-format yuv420p` it takes exactly as long as ffmpeg, thanks! Still curious why Handbrake is even faster, though, do you have any ideas?

**Comment by alexheretic** [comment]
Thanks for confirming, no I've no idea about what handbrake is doing vs ffmpeg here.
