### ISSUE TITLE
How to set audio bitrate when using auto-encode?

### ISSUE THREAD

**Issue by SamTheRuby** [alexheretic/ab-av1#184]
Hi quick question, If I have a command that looks like this:
ab-av1.exe auto-encode --input "%%f" --encoder libx265 --preset slow --min-vmaf !minVmaf! --max-encoded-percent !maxEncodedPercent! --min-crf 5 --max-crf 24 --thorough --crf-increment 0.5 --acodec libopus

where would I specify the audio bitrate if I want to use opus at 192kbps with vbr on?

**Comment by alexheretic** [comment]
You can do this using `--enc` to submit the ffmpeg option.

**Comment by SamTheRuby** [comment]
how do I specify 2 commands such as b:a=192k and vbr on? what is the proper syntax?

**Comment by SamTheRuby** [comment]
> You can use `--enc` multiple times to specify multiple ffmpeg options.

That worked, thanks!

**Comment by SamTheRuby** [comment]
> You can use `--enc` multiple times to specify multiple ffmpeg options.

That worked, thanks!
