### ISSUE TITLE
Encode a clip in chunks based on a a specific VMAF

### ISSUE THREAD

**Issue by samtheruby1012** [alexheretic/ab-av1#186]
Hi I wanted to find out if it would be possible to implement a feature to auto-encode that makes it that a specified minimum VMAF can be supplied (for example 95) and that the auto encode should encode the clip adjusting the CRF per sample taken to target that specified minimum VMAF,  so that in the clip the minimum the VMAF will be is 95.

**Comment by alexheretic** [comment]
This sounds pretty much what auto-encode already does.

Or do you mean to sample the entire file in chunks and to encode each chunk with different crfs according to the vmaf target? If so this is roughly what [av1an](https://github.com/master-of-zen/Av1an) project does. The idea of ab-av1 is to make the VMAF analysis fast, sampling only parts of the video, then encode with a single crf value.

**Comment by SamTheRuby** [comment]
[av1an](https://github.com/master-of-zen/Av1an) still targets 5 percentile lows while ab-av1 targets a exact vmaf, which is much more in line with what I want to do

**Comment by BankaiNoJutsu** [comment]
Hey, i've been experimenting a bit with this idea, inspired by av1an.
https://github.com/BankaiNoJutsu/media-db

specifically the pipe_vmaf_threaded_2 mode.

you can try it with:
.\cli.exe -m pipe_vmaf_threaded -e hevc_qsv -v 95 --verbose -t 4 -o . -i '.\file.mkv'

note that it's unfinished, just an idea put into test.
Messy code and i can't recall if it was actually doing it's fully intended purpose. But hopefully food for thought.

**Comment by SamTheRuby** [comment]
@BankaiNoJutsu Im assuming I have to build it from source?

**Comment by SamTheRuby** [comment]
Ill definitely run some test for you @BankaiNoJutsu

**Comment by alexheretic** [comment]
I think this is just a different approach overall to ab-av1, good luck with it.
