### ISSUE TITLE
Auto-encode but encode not working

### ISSUE THREAD

**Issue by haoliangzhao** [alexheretic/ab-av1#194]
Hi. When I use auto-encode mode, the crf-search phase works well, but the encoding phase does not work. It stucks forever, and the CPU load is very low, indicating the encoding process is not running.
I have ffmpeg in PATH. But I don't have SvtAv1EncApp.exe binary.

~~SOLVED: Installing SvtAv1EncApp.exe solves the problem. Nevertheless I don't understand why the encoding phase still invokes SvtAv1EncApp.exe, given that ffmpeg.exe already contains the svt-av1 encoder.~~

EDIT: The problem is not solved. I've found that if the source file is in .mov, the encoding phase never works. Even more, if the source file is in .mp4, the encoding phase sometimes works, sometimes doesn't. I'm using the latest release on a Windows 10 22H2

**Comment by alexheretic** [comment]
svt-av1 binary _was_  used in older versions before v0.7. What version of ab-av1 are you using? Can you try the latest?

**Comment by haoliangzhao** [comment]
> svt-av1 binary _was_ used in older versions before v0.7. What version of ab-av1 are you using? Can you try the latest?

I'm using the latest release. Also I confirm that the svt-av1 binary is not necessary.

**Comment by alexheretic** [comment]
If encoding is not working it sounds like ultimately an ffmpeg issue. ab-av1 is just using ffmpeg. However, if ab-av1 is using ffmpeg wrongly it is a bug we can fix here. There isn't enough info here for me to do much with. I'll close for now we can re-open with more info.
