### ISSUE TITLE
Not working under Windows 11

### ISSUE THREAD

**Issue by haoliangzhao** [alexheretic/ab-av1#195]
So I freshly reinstalled a Windows 11 23H2, and I'm using Windows PowerShell. When I run `ab-av1.exe`, it outputs nothing.

```
PS C:\Users\lucius\Desktop> .\ab-av1.exe
PS C:\Users\lucius\Desktop>
```

Other commands, like `ffmpeg.exe`, work just fine.

SOLVED: the problem is caused by a missing of the VCRUNTIME140.dll. Installing "Microsoft Visual C++ 2015 - 2022 Redistributable" will fix it. See [here](https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-and-msvcp140dll-missing-in-windows/caf454d1-49f4-4d2b-b74a-c83fb7c38625).

**Comment by alexheretic** [comment]
Not sure if there is anything we can improve here. Maybe add this info to https://github.com/alexheretic/ab-av1/wiki/Troubleshooting?
