### ISSUE TITLE
Question: How does vmaf work for downscaling

### ISSUE THREAD

**Issue by cliveong** [alexheretic/ab-av1#196]
If I have 4k content that I want to reencode to 1080p, does the vmaf searching work?

Does it downscale to 1080p then perform the search or search in 4k then downscale?

**Comment by alexheretic** [comment]
During the crf-search the same user `--vfilter` specified is applied to the reference video samples for comparison with the distorted samples.

* Each sample is cut from the reference, unchanged
* Each sample is encoded as specified (in your case downsampled)
* vmaf is then run comparing the reference samples + vfilter to the encoded samples
