### ISSUE TITLE
Feature request: Support for av1_nvenc

### ISSUE THREAD

**Issue by doihaveto** [alexheretic/ab-av1#201]
Would it be at all possible to add support for Nvidia's av1_nvenc encoder?

**Comment by alexheretic** [comment]
It may be, can you provide an example ffmpeg invocation?

**Comment by doihaveto** [comment]
> It may be, can you provide an example ffmpeg invocation?

`ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i original.mkv -c:v av1_nvenc -preset p7 -cq 35 -c:a copy av1.mkv`

**Comment by alexheretic** [comment]
nvenc -cq is actually already supported since #107 that may be enough for your user case. You can use, potentially multiple, --enc-input & --enc args to configure the hwaccel ffmpeg options.

**Comment by doihaveto** [comment]
Yes, that worked. Thanks!
For anyone wondering, the command for it is:
`ab-av1 auto-encode -i original.mkv --encoder av1_nvenc --preset p7 --max-crf 51 -o av1_nvenc.mkv`
