### ISSUE TITLE
JPEG-XL support

### ISSUE THREAD

**Issue by gitoss** [alexheretic/ab-av1#203]
FFMPEG now supports JPEG-XL: https://ffmpeg.org/ffmpeg-codecs.html#libjxl

I'm already using AB-AV1 to to crf-search a target vmaf for avif images. It would be nice to have this support for JPEG-XL, too - even though unlike AV1, JPEG-XL is an image-only codec.

Since JPEG-XL uses FFMPEG just like AVIF, adding JPEG-XL should probably not be complex?

I know it could be already be done using the 'ab-av1 vmaf' command and encoding to JPEG-XL until it reaches the target vmaf - but 'ab-av1 crf-search" would save a lot of hassle.

**Comment by mr44er** [comment]
I don't know how this would be useful. The internal encoder of jxl already has the option for distance=1, which is THE visually lossless mode like VMAF95.
`cjxl --distance=1 --lossless_jpeg=0 inputfile.xxx output.jxl`

**Comment by gitoss** [comment]
> I don't know how this would be useful. The internal encoder of jxl already has the option for distance=1, which is THE visually lossless mode like VMAF95. `cjxl --distance=1 --lossless_jpeg=0 inputfile.xxx output.jxl`

It's about vmaf targets that are NOT virtually lossless - I´m using vmaf 85 or 90 to get optimum file size for still reasonable visual loss.

**Comment by mr44er** [comment]
I recommend that you try it out. --distance 2 or --distance 3 really makes small files. -d3 is definitely NOT 97% of original file size, if you have that in mind.

**Comment by gitoss** [comment]
Ok, if you say that xl's distance param is about the same as vmaf then it's not necessary to add it to abc-av1. I faintly remember that vmaf was removed from xl some time ago, maybe that was the reason.

**Comment by mr44er** [comment]
It is not exact the same as VMAF (well, -distance 1 would be VMAF100), but see it from this point: with the example-picture you're with -distance 3 already at ~50% of original file size. Do you see the quality differences between them? If not, you can use -distance 3 for everything.

It is not exactly correct (my guess), but orient yourself like this:
VMAF100=distance 1, VMAF95=distance 2, VMAF90=distance 3 ...etc.

Btw. expecting the picture coming out with -distance 4 at ~400KB it's unlikely that anybody will need/use -distance 5,6,7
