### ISSUE TITLE
Sample size parameter?

### ISSUE THREAD

**Issue by five82** [alexheretic/ab-av1#206]
Could the sample size of 20 seconds be modifiable through a parameter? I'm encoding video segments that are 2 to 3 minutes in length so 20 second samples are too long for my use case. Thanks.

**Comment by mr44er** [comment]
With very short video segments short(er) samples are counterproductive.

I would then see the whole segment as sample and encode this multiple times with good guesses and different CRF.

**Comment by alexheretic** [comment]
Yes I think this should be configurable. Currently it is hardcoded to 20s, just needs a small rework to wire it up to a command arg.

**Comment by alexheretic** [comment]
`--sample-duration` will be in the next version
