### ISSUE TITLE
HW Encoders ratecontrol

### ISSUE THREAD

**Issue by raysv** [alexheretic/ab-av1#216]
Hi, 
Not realy a bug, but a question since i'm not able to find the info.

Notice that the crf-search do work for HW encoders, but what ratecontroll instead of CRF?

is it LA_ICQ for qsv?

What about nvenc, is it cq or qp ?

**Comment by alexheretic** [comment]
Hello. Though the tool was designed with crf in mind, I'd like to make the ffmpeg `-crf` usage configurable (#135).

There are some encoder specific hardcoded overrides currently: See https://github.com/alexheretic/ab-av1/blob/main/src/ffmpeg.rs#L213
