### ISSUE TITLE
Failing when useing Intel ARC with either hevc/av1_qsv encoder

### ISSUE THREAD

**Issue by raysv** [alexheretic/ab-av1#217]
When useing arc card it failes with:

Unrecognized option 'look_ahead'.
Error splitting the argument list: Option not found

**Comment by zedstate** [comment]
I've been using the command below to search/encode using Intel QuickSync on Intel ARC:

ab-av1.exe  crf-search -i input.mkv -e av1_qsv --preset veryslow --min-vmaf 96

The '--preset veryslow' option will enable ICQ with look ahead.   Turn on debugging using the environment variables to see the actual ffmpeg commands.    Toggle on the Intel Arc overlay (on Windows) to see the media engine engage for the encodes.   Hope this helps.

**Comment by alexheretic** [comment]
I don't have intel hardware to test with myself. If people have working args perhaps we could add a page like https://github.com/alexheretic/ab-av1/wiki/Encoders for these hw encoders?

**Comment by lovelytwo** [comment]
Hi raysv,

I'm guessing you are passing the -look_ahead option directly to ab-av1? However ab-av1 requires options you want to pass to ffmpeg to be passed though --enc or --enc-input. The former being encoder options, and the later be input options.

Eg here is my av1_qsv command line.

ab-av1 crf-search --pix-format yuv420p -i <input-file> --min-vmaf 95 --preset slow --max-encoded-percent 80 --min-samples 6 --encoder av1_qsv --enc qsv_device=/dev/dri/renderD128 --enc extbrc=1 --enc look_ahead=1 --enc look_ahead_depth=100 --enc g=240 --enc b_strategy=1 --enc adaptive_i=1 --enc adaptive_b=1 --min-crf 18 --max-crf 32

Hope this helps.

**Comment by raysv** [comment]
I'm not, thats the problem:

.cargo/bin/ab-av1 crf-search --pix-format yuv420p10le --min-vmaf 95 --preset slow --max-encoded-percent 80 --min-samples 6 --encoder hevc_qsv -i /media/test/file.mkv 
  00:00:00 ########################################################################################################################################################################################################################################################################### (sampling crf 32, eta 0s)Error: ffmpeg encode_sample exit code 8
----cmd-----
ffmpeg -y -i /home/raysv/.ab-av1-LQTjBwWuUoq6/The Vampire Diaries (2009) - S02E01 - The Return [Bluray-1080p Remux][DTS-HD MA 5.1][AVC]-FraMeSToR.sample341+480f.mkv -c:v hevc_qsv -g 240 -look_ahead 1 -extbrc 1 -look_ahead_depth 40 -global_quality 32 -pix_fmt yuv420p10le -preset slow -an /home/raysv/.ab-av1-LQTjBwWuUoq6/file.sample341+480f.hevc_qsv.crf32.slow.mkv
---stderr---
ffmpeg version N-117623-g3565903c63 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
  configuration: --prefix=/home/raysv/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/raysv/ffmpeg_build/include --extra-ldflags=-L/home/raysv/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/home/raysv/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libvmaf --enable-nonfree
  libavutil      59. 44.100 / 59. 44.100
  libavcodec     61. 22.100 / 61. 22.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.100 / 10.  6.100
  libswscale      8.  6.100 /  8.  6.100
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
Unrecognized option 'look_ahead'.
Error splitting the argument list: Option not found

**Comment by raysv** [comment]
oh lord, was running two ffmpegs on the system, and the one ab-av1 was using i had forgot to build with enabled libvpl !!
