### ISSUE TITLE
Feature: expand in-progress info for `crf-search` as seen when debugging is enabled

### ISSUE THREAD

**Issue by stderr-to-devnull** [alexheretic/ab-av1#219]
After enabling the debugging, I saw `[INFO]` level information relayed during in-progress `crf-search` which I found quite useful and helpful and would like to see it relayed in an optimal way during normal progress.

The debug info in scope:

`[2024-09-04T23:12:21Z INFO  ab_av1::command::sample_encode] encoding sample 10/16 crf 18`

Desired in-progress extra info: `encoding sample 10/16 crf 18`

1. It is useful to see how many samples were generated, in my case I use just `--sample-every`.
2. It is useful to see the sample progress (`10/16`) for a given `crf` value, sort of like a secondary progress indicator.

**Comment by alexheretic** [comment]
Yes I think this would be useful. You can see this info already using `ab-av1 sample-encode`, `crf-search` and `auto-encode` are built on top and didn't have quite as easy access to the info relevant to the `sample-encode` bit. But it is possible for that to be shared and to add simple info to the other higher level commands.
