### ISSUE TITLE
x265 VMAF estimations are consistently higher than full analysis of encode at same settings

### ISSUE THREAD

**Issue by stderr-to-devnull** [alexheretic/ab-av1#220]
>I acknowledge that this may not be an issue with `ab-av1` so any suggestions are welcome
>I also observed that this issue does not manifest (rather it is minimal) when using `AV1`

#### Below I made a table with initial _standardized_ settings, with videos between 20-40min, encoded at `CRF17`

Estimates obtained with this command:

```sh
.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --sample-every=5m -e libx265 --preset=slow --vfilter scale=-1:540:flags=lanczos
```

| Source resolution | Source bitrate | Encoder | Target CRF | Preset | Projected VMAF | Analyzed VMAF of encode
|-------------------|----------------|---------|------------|--------|----------------|------------------------
| 4096x2160         | 18.9 Mb/s      | x265    | 17         | slow   | 93.24          | 91.70
| 1920x1080         |  7.6 Mb/s      | x265    | 17         | slow   | 94.99          | 93.35
| 3840x2160         | 15.0 Mb/s      | x265    | 17         | slow   | 92.69          | 90.01

#### Below are exhaustive tests made on an 1h+ 1080p 60fps video, encoded at `CRF 17` with same settings used in VMAF estimations (see below)

Full VMAF _ground truth_ of encode, for VMAF default and `n_subsample=5`

```sh
.\ab-av1.exe vmaf --reference-vfilter scale=-1:540:flags=lanczos --vmaf n_subsample=5 --reference "1080p.mp4" --distorted "1080p.mkv"
93.04958
.\ab-av1.exe vmaf --reference-vfilter scale=-1:540:flags=lanczos --reference "1080p.mp4" --distorted "1080p.mkv"
93.04889
```

VMAF estimations at various sample numbers and durations

```sh
.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --vmaf n_subsample=5 --samples=6 --sample-duration=30s -e libx265 --enc x265-params=no-sao:aq-mode=4:ctu=32 --preset=slow --vfilter scale=-1:540:flags=lanczos -i "1080p.mp4"
- crf 17 VMAF 95.78 (74%)

.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --vmaf n_subsample=5 --samples=7 --sample-duration=30s -e libx265 --enc x265-params=no-sao:aq-mode=4:ctu=32 --preset=slow --vfilter scale=-1:540:flags=lanczos -i "1080p.mp4"
- crf 17 VMAF 95.87 (73%)

.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --vmaf n_subsample=5 --samples=5 --sample-duration=35s -e libx265 --enc x265-params=no-sao:aq-mode=4:ctu=32 --preset=slow --vfilter scale=-1:540:flags=lanczos -i "1080p.mp4"
- crf 17 VMAF 96.62 (67%)

.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --vmaf n_subsample=5 --samples=10 -e libx265 --enc x265-params=no-sao:aq-mode=4:ctu=32 --preset=slow --vfilter scale=-1:540:flags=lanczos -i "1080p.mp4"
- crf 17 VMAF 95.73 (71%)

.\ab-av1.exe crf-search --min-crf=15 --max-crf=19 --min-vmaf=93 --vmaf n_subsample=5 --samples=10 --sample-duration=30s -e libx265 --enc x265-params=no-sao:aq-mode=4:ctu=32 --preset=slow --vfilter scale=-1:540:flags=lanczos -i "1080p.mp4"
- crf 17 VMAF 95.78 (71%)
```

#### Conclusion

VMAF score estimates for `x265` consistently overshoot by 2 - 2.5+ compared to full `VMAF` analysis at basically any reasonable settings used for analysis.

**Comment by alexheretic** [comment]
Sampling accuracy depends on the source video. You can up the samples up to doing full pass analysis. Full pass is accurate but slow.

**Comment by stderr-to-devnull** [comment]
> Sampling accuracy depends on the source video. You can up the samples up to doing full pass analysis. Full pass is accurate but slow.

Of course I am aware of that. I was reporting that the overshoot is significant in the case of `x265` for some reason, even with more accuracy options like number of samples and sample length, compared to `AV1`. For clarity, I will repost the above table but now also with `AV1` measurements, using the same standard estimations:

| Source resolution | Source bitrate | Encoder | Target CRF | Preset | Projected VMAF | Analyzed VMAF of encode
|-------------------|----------------|---------|------------|--------|----------------|------------------------
| 4096x2160         | 18.9 Mb/s      | x265    | 17         | slow   | 93.24          | 91.70
|                   |                | SVT-AV1 | 23         | 4      | 93.69          | 93.10 (PSY)
|                   |                | SVT-AV1 | 25         | 4      | 92.83          | 92.47 (PSY)
| 1920x1080         |  7.6 Mb/s      | x265    | 17         | slow   | 94.99          | 93.35
|                   |                | SVT-AV1 | 25         | 4      | 94.78          | 94.23 (PSY)

As it can be observed, even when `AV1` flavors differ -> full encodes are actually using `SVT-AV1-PSY`, the estimations are considerably closer to _ground truth_. So regarding `x265`, even using twice as many samples at +50% sample duration, the estimations are still considerably higher for some reason.

Besides applying an arbitrary offset and extrapolating that an estimation of `95` VMAF will result in a `93` VMAF, are there other ways of minimizing this overshoot?

**Comment by stderr-to-devnull** [comment]
Alright there is an issue with passing `x265-params` none of these are passed except for `profile=main10` for some reason. As shown above, I used: ` --enc x265-params=profile=main10:no-sao:aq-mode=4:ctu=32`

I also tried like this ` --enc x265-params=profile=main10,no-sao,aq-mode=4,ctu=32`

There is no error thrown, parameters are simply ignored, I checked the output.
