### ISSUE TITLE
Feature: batch processing based on a simple list written in a file

### ISSUE THREAD

**Issue by stderr-to-devnull** [alexheretic/ab-av1#221]
Maybe a simple CSV file:

```sh
# input,output
path/to/video1.mp4,path/to/video1_out.mkv
path/to/video2.mp4,path/to/video1_out.mkv
```

- if output path is ignored, use same as input path
- if file name is also ignored, use a diversified or configurable suffix, right now from the help I see it only knows to append `av1` to output file name
- ideally, the suffix could/should be configurable in the command line

PS: would love to see someone write a GUI for this, unfortunately I do not have the skills

**Comment by alexheretic** [comment]
It is generally straightforward to script this outside of the ab-av1 binary, and very flexible. So I'm not convinced this functionality should be included where that flexibility would be harder and bloat the code. Otoh perhaps there is a good case for this I'm missing?

> if file name is also ignored, use a diversified or configurable suffix, right now from the help I see it only knows to append av1 to output file name

The current output name appends a suffix based on the vcodec used, so by default "av1" as svt-av1 is the default vcodec.

> ideally, the suffix could/should be configurable in the command line

I'd consider that, though it kinda already is configurable in that you can provide `-o` with exactly how you want it to be. -o is maximally flexible too. I suppose the default behaviour is just meant to be nice in that you don't have to specify an output and you get something that makes sense. Ofc I'd consider suggestions to improve that default behaviour.

**Comment by mr44er** [comment]
This loops over all .mp4 files in a folder and outputs as file1.av1.mp4 ...file9.av1.mp4. If no CRF is found, this file will be skipped.
` for f in *.mp4; do ab-av1 auto-encode --thorough -i "${f}"; done`

**Comment by stderr-to-devnull** [comment]
> It is generally straightforward to script this outside of the ab-av1 binary, and very flexible. So I'm not convinced this functionality should be included where that flexibility would be harder and bloat the code. Otoh perhaps there is a good case for this I'm missing?
I was actually thinking to write a wrapper script for `ab-av1` but I can only do that competently in BASH and the machine I am running `ab-av1` on has Windows installed. Sure, there is `WSL` but I think I would unnecessarily complicate things for myself. The mentioned reduced flexibility is not an issue, as this feature would be added as a new argument which people can choose to use or not.

The case for this feature request would be:
- expanding functionality and flexibility
- allowing greater use case for people who are not technical enough to write their own wrappers
- functionality would be universal, not OS dependent (because `ab-av1` is also released as Windows binary)

> > if file name is also ignored, use a diversified or configurable suffix, right now from the help I see it only knows to append av1 to output file name
> 
> The current output name appends a suffix based on the vcodec used, so by default "av1" as svt-av1 is the default vcodec.

For my use case I would want `ab-av1` to automatically append suffixes based on a defined value (ex. 540p) and/or the CRF value used on `auto-encode`.

> > ideally, the suffix could/should be configurable in the command line
> 
> I'd consider that, though it kinda already is configurable in that you can provide `-o` with exactly how you want it to be. 

Yes, I always use `-o`. I was referring to this feature in the context of implementing the file list, not necessarily by itself (though even this would not hurt). In my workflow, I supply files from different paths so it would not be as easy as doing an iteration over a target path.

Right, so what I am getting from the response is the intent for this tool to be focused on its main functions and not add to it more features that do not directly relate to its core functionality. Basically the `KISS` principle which has merit. Though I would argue that `auto-encode` is also outside the core functionality but nonetheless it is a great and welcome feature. I was thinking that adding the list functionality would be trivial.

Unless the author does not wish to implement the feature, this issue can be closed.
I will explore the option of a shell script inside WSL and/or maybe learn a bit of PowerShell.
