### ISSUE TITLE
Buggy libx265 & libx264 because encoding to .avif instead of .265 / .264

### ISSUE THREAD

**Issue by gitoss** [alexheretic/ab-av1#225]
The main repo page states "Also supports other ffmpeg compatible encoders like libx265 & libx264" https://github.com/alexheretic/ab-av1/blob/main/README.md

Did anyone actually try that? :-) 

There is a simle bug: the ffmpeg command initiated by ab-av1 (crf-search) tries to encode to .avif, which makes ffmpeg fail with "[avif] Could not find tag for codec hevc in stream #0, codec not currently supported in container".

Simply replacing .avif with .265 or .264 solves this, the vmaf score calculation works fine even with these raw containers.

Please do keep the libx265 option, it's nice to search for a suitable crf for later encoding with libheif.

**Comment by alexheretic** [comment]
The tool is primarily aimed at videos, I assume you are instead using it for images?

The current default output extension logic is quite simple: https://github.com/alexheretic/ab-av1/blob/859999b26a72b55817950e2842c2dd52991edb38/src/command/encode.rs#L159

For images it indeed just picks .avif, I guess as encoding them was the only motivation for image support at the time. It seems fairly easy to add logic to pick different default extensions for different encoders.

**Comment by alexheretic** [comment]
Thanks for the info. I wasn't aware .265, .264 extensions were even a thing :sweat_smile:
