### ISSUE TITLE
CRF-SEARCh with nvenc way off based compared to finished product score

### ISSUE THREAD

**Issue by raysv** [alexheretic/ab-av1#228]
Hi, 
was about to check out how nvenc is fearing with HEVC now, and did two Episodes of a series to test. 
Useing crf-search with min-samples 6, and with the crf its giving me, it should produce vmaf score of 95. 
However, when i after encoding it run a full vmaf check on both episodes, the actuall vmaf ended up being vmaf 40.6 and 41.7.

Any snuggestions to why this might happend?  The size of the files however is pretty spot on.

**Comment by alexheretic** [comment]
Taking samples to estimate overall quality isn't exact. It's a trade-off. You can try taking more samples up to doing full pass analysis which is exact but obviously slower.

**Comment by mr44er** [comment]
The source codec (VC1) is never the problem, it is mostly variable framerate.

Just a guess, but try it: https://github.com/alexheretic/ab-av1/issues/238#issuecomment-2495499973
