### ISSUE TITLE
Add VVenC Support

### ISSUE THREAD

**Issue by veryprogram** [alexheretic/ab-av1#229]
With FFᴍᴘᴇɢ 7.1 [classifying VVC decoding as now being stable](https://www.phoronix.com/news/FFmpeg-7.1-Released), FFᴍᴘᴇɢ having [optional support for VVC encoding via VVenC](https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration), apps like [Shutter Encoder enabling VVC encoding](https://www.shutterencoder.com) via a GUI, and VVC being [even more efficient than AV1](https://www.mdpi.com/2079-9292/13/5/953) with regard to the video file sizes necessary to achieve similar visual quality, I hope ab-av1 also gains support for calculating which QP to use to achieve VMAF 95.

My hard drives are crying out for an even more efficient way to store archival video encodes.

**Comment by raysv** [comment]
Any clients supporting this? :D

**Comment by alexheretic** [comment]
If ffmpeg can use an encoder then ab-av1 should also be able to with `-e`. Is there anything else this vcodec would need from this project rather than ffmpeg?

**Comment by alexheretic** [comment]
afaics there is no work needed here since we already support any ffmpeg vcodec. Let me know if there are any tweaks required for this vcodec.

**Comment by DenysFontaine** [comment]
Hi There,

VVC don't use CRF, but QP.  I think you should make an exeption on your code ?  Right ?

**Comment by raysv** [comment]
CFR  or qp is an encoder thing, not codec
