### ISSUE TITLE
Flag to switch priority of the spawned ffmpeg process

### ISSUE THREAD

**Issue by hyoretsu** [alexheretic/ab-av1#230]
Setting it to "below normal" comes at a slight time increase but makes the PC a lot more usable.

**Comment by alexheretic** [comment]
This is a pretty reasonable thing to do when encoding, I usually encode at low priority myself. But it isn't something I would expect a cli tool to have flags for, I'd generally expect OS tools to control this. E.g. on Linux I'd use `nice ab-av1 ...`.
