### ISSUE TITLE
Terminal broken again after crf-search

### ISSUE THREAD

**Issue by lynix** [alexheretic/ab-av1#231]
I've got the same issue as in #51. I think noteworthy is that, when the results cache is hit, the issue is not there. So maybe it is indicatif again?

- ab-av1 0.7.18
- up-to-date Arch x86_64

**Comment by raysv** [comment]
Can report the same issue on up-to-date ubuntu :)

**Comment by alexheretic** [comment]
Thanks for the report, I found vmaf ffmpeg process inheriting stdin could be causing this. Will be fixed in the next version if that is the case. I wonder why this doesn't affect fish shell at all.
