### ISSUE TITLE
[Question] Can you pause ab-av1?

### ISSUE THREAD

**Issue by 9Oc** [alexheretic/ab-av1#239]
Is there a way to pause ab-av1 when doing a vmaf or crf-search command and then later un-pause and resume where it left off?

Using v0.8.0 on windows 10.

**Comment by alexheretic** [comment]
Nothing baked into the program. However, on Linux you can stop the process tree and then later continue. So this feature is something I'd consider the OS process/task manager being responsible for rather than the program itself. I'm not sure how it works on Windows exactly but I would assume you can do the same thing there.

**Comment by 9Oc** [comment]
> Nothing baked into the program. However, on Linux you can stop the process tree and then later continue. So this feature is something I'd consider the OS process/task manager being responsible for rather than the program itself. I'm not sure how it works on Windows exactly but I would assume you can do the same thing there.

I looked up on windows and there seemed to be a few solutions to "halt" execution of whatever is happening inside the terminal but none of them actually paused, they either didn't do anything or actually broke out of the current command entirely. Tried to find a way to possibly do it in task manager but no luck there either.

I would agree that in CLI probably it is on the OS to have true pause functionality but I don't think there is on windows from what I can see that functions as a true pause rather than a stop. Not really a big issue since it is not something I've needed to use frequently but I have had times where it'd come in handy. If you ever have the free time and want to add it into ab-av1 itself it'd be swell, thanks for your work

**Comment by alexheretic** [comment]
It is actually something I have used in the past, though on Linux. I tend to do background runs using [pueue](https://github.com/Nukesor/pueue) and `pueue pause` works a treat for this (then later `pueue start`).

I see pueue supports Windows so perhaps this feature works there too and would suit your needs?

**Comment by 9Oc** [comment]
Just tried and it does work for me on windows 10, although slight janky but it gets the job done. Thanks sir

**Comment by 9Oc** [comment]
Also unrelated to this question but though I'd ask while you were here, what is a potential reason why during crf-search command the vmaf portion of the search on each sample runs at 90-120+ fps, but when I run a vmaf command on my finished encode and source file it is analyzing it at around 20-30fps? Is it just because the files are much larger and have more complexity since they aren't small samples?

**Comment by alexheretic** [comment]
> Also unrelated to this question but though I'd ask while you were here, what is a potential reason why during crf-search command the vmaf portion of the search on each sample runs at 90-120+ fps, but when I run a vmaf command on my finished encode and source file it is analyzing it at around 20-30fps? Is it just because the files are much larger and have more complexity since they aren't small samples?

Hmm no idea, I would have expected a similar rate to the sample.

**Comment by 9Oc** [comment]
To give you more info I am using the same x265 settings passed through the crf-search command that I'm using when running the vmaf command on the same source file. I thought maybe at first it was due to my hard drive being bottlenecked having its read speed capped by other programs at the same time but I ran ab-av1 on its own to make sure and that didn't make a difference. Anyways, not a big deal it's still plenty fast, if you need any info from me like logs or other specs of my system/the files im analyzing let me know
