### ISSUE TITLE
[REQUEST] Extend support for qscale (rather than crf) for mpeg2video/H.262 DVD-Video.

### ISSUE THREAD

**Issue by bbgdzxng1** [alexheretic/ab-av1#245]
Alex,

I really like the ab-av1 tool, it is great.  It was such a great enhancement to add support for other codecs.

Would you consider adding support for qscale in addition to crf, so that codecs such as mpeg2video that do not support crf can be used?  The use case is for mpeg2video/H.262 DVD-Video production, where both quality and prediction of file size are both useful.

I was successful in (ab)using the tool to ignore crf and pass in qscale through encoder arguments - and that works great in a non-iterative mode.  In this command, the crf values are basically ignored and the user must perform the iteration manually...

`$ ab-av1 crf-search --input "./capture.ts" --cache false --min-vmaf 95 --min-crf 0 --max-crf 1 --crf-increment 1.0 --vmaf-scale 852x480 --encoder 'mpeg2video' --enc 'qscale:v=2' --enc 'maxrate:v=9800000' --enc 'bufsize:v=1835008' --enc 'g:v=18'`

A minimal hack would be to have a synonym/alias mode (something like --crf-alias=qscale or --crf-alias=q) where the tool replaces the -crf option name with -qscale (or any custom string) when invoking FFmpeg.  It would not matter that the UI still refers to the term CRF.  mpeg2video's qscale could still be controlled by CRF values in a similar sane range of [2..32] with --min-crf/max-crf/crf-increment`, the proposed functionality would be a run-time replacement of the -crf param with a custom string when FFmpeg is invoked.  qscale and crf are both of similar orders of magnitude.  The search algo would be similar.

Passing -qscale / -q through encoder arguments works, this proposal would unlock iteration for mpeg2video & DVD-Video.  It would also allow the user to see the effect of other encoding arguments such as custom quantization matrices (which were popular on doom9 back in the pre-VMAF days) on the search result.

Great tool.

Feel free to close and mark as "Won't Fix" if this suggestion is not of interest.  Thanks again.

**Comment by bbgdzxng1** [comment]
Closing...  Dupe of https://github.com/alexheretic/ab-av1/issues/135

**Comment by alexheretic** [comment]
#135 is so you can override and use different quality args. We should also act as best we can by default if possible, so I raised #252 with better defaults for mpeg2video.
