### ISSUE TITLE
XPSNR fails on very similar or identical pictures (score: inf)

### ISSUE THREAD

**Issue by gitoss** [alexheretic/ab-av1#256]
... continuing from https://github.com/alexheretic/ab-av1/issues/244 :-)

AB-AV1 0.9 fails with an ugly ffmpeg output on very similar or identical pictures because the xpsnr score isn't numeric, but 'inf' (try to run ab-av1.exe xpsnr --reference same.png --distorted same.png

```
[Parsed_xpsnr_0 @ 0000000000f36540] XPSNR  r: inf
XPSNR average, 1 frames  r: inf  g: inf  b: inf  (minimum: inf)
[out#0/null @ 0000000000f004c0] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.434x
```

A possible hotfix could be to simple limit the xpsnr score to 99 (and map inf to 99, too) - on the logarithmic psnr scale 50-ish is lossless, so 99 should be a safe 'inf' dummy value.

Otherwise thanks for implementing, xpsnr seems to be a bit faster than vmaf which is nice for bulk crf-search image conversion.

**Comment by alexheretic** [comment]
Thanks, should be straightforward to fix. I'll look when i get some time.
