### ISSUE TITLE
XPSNR calculation results too low

### ISSUE THREAD

**Issue by veikk0** [alexheretic/ab-av1#258]
I've been testing out the XPSNR feature in v0.9.0  (thanks btw, it was a nice Christmas gift). So far I've had pretty good experiences with it.

However, I'm running into an issue with some files where the values from XPSNR calculations are much too low compared to the actual visual quality, resulting in failures to find a suitable CRF with some input files.

It looks like the VMAF frame sync issue from a couple years ago, and probably has the same root cause. The FFmpeg command that runs when calculating XPSNR doesn't set the input frame rate manually with `-r`, and when there's a frame desynchronization, the resulting XPSNR value is completely out of whack.

I was able to confirm this by manually encoding some of the sample files cut by ab-av1 from a source file that exhibits this issue and calculating XPSNR with and without `-r 60` as an input option for both source and ref. Without `-r 60`, I got an XPSNR value of 32.0101, and with `-r 60` I got 40.8062. Since (X)PSNR uses a logarithmic scale, that's basically like getting a VMAF of 60 or lower when the ground truth is ~93.

Maybe there should be a `--xpsnr-fps` option, just like the new `--vmaf-fps`? Or perhaps they could be combined into a shared option, since only one metric is used at a time anyway.

**Comment by alexheretic** [comment]
Ok, perhaps also the `setpts=PTS-STARTPTS,settb=AVTB` filter we apply for vmaf would help? I don't have a test video that reproduces this issue, so this is harder to maintain than I'd like. 

Does `-r 25` work just as well? It would be slightly simpler to use the same default as vmaf-fps arg.

**Comment by veikk0** [comment]
`-r 25` works. However, FFmpeg crashes when I try to use the `setpts` filter with xpsnr ("Floating point exception (core dumped)"), and filing a bug report with FFmpeg is a bit too far into the weeds I'm willing to go right now.

`-r 25` seems like the way to go.

**Comment by alexheretic** [comment]
Test across my sample videos ref vs svt-av1 distorted sample it seems `-r 60` gives the best score regardless of video fps. Having no rate seems to yield worse scores for most cases.

This suggests we should default `--xpsnr-fps 60`.

<details>
  <summary>Test results</summary>
  
 ### pixabay-turntable-8453.sample14+500f.mkv vs pixabay-turntable-8453.sample14+500f.av1.crf25.10.mp4 

ref:   `Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](eng): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 1920x1080, 542 kb/s, 25 fps, 25 tbr, 12800 tbn (default)`

* No -r: `XPSNR  y: 39.8218  u: 41.2314  v: 41.4515  (minimum: 39.8218)`
* -r 23.98: `XPSNR  y: 39.8218  u: 41.2314  v: 41.4515  (minimum: 39.8218)`
* -r 25: `XPSNR  y: 39.8218  u: 41.2314  v: 41.4515  (minimum: 39.8218)`
* -r 29.98: `XPSNR  y: 39.8218  u: 41.2314  v: 41.4515  (minimum: 39.8218)`
* -r 30: `XPSNR  y: 39.8218  u: 41.2314  v: 41.4515  (minimum: 39.8218)`
* -r 59.94: `XPSNR  y: 40.1159  u: 41.4778  v: 41.7167  (minimum: 40.1159)`
* -r 60: `XPSNR  y: 40.1159  u: 41.4778  v: 41.7167  (minimum: 40.1159)`
* -r 119.88: `XPSNR  y: 40.1159  u: 41.4778  v: 41.7167  (minimum: 40.1159)`
* -r 120: `XPSNR  y: 40.1159  u: 41.4778  v: 41.7167  (minimum: 40.1159)`
* -r 240: `XPSNR  y: 40.1159  u: 41.4778  v: 41.7167  (minimum: 40.1159)`


### pixabay-lemon-82602.sample16+500f.mkv vs pixabay-lemon-82602.sample16+500f.av1.crf25.10.mp4 

ref:   `Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 3840x2160, 25 fps, 25 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](eng): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 3840x2160, 4930 kb/s, 25 fps, 25 tbr, 12800 tbn (default)`

* No -r: `XPSNR  y: 41.3326  u: 39.9754  v: 42.0654  (minimum: 39.9754)`
* -r 23.98: `XPSNR  y: 41.3326  u: 39.9754  v: 42.0654  (minimum: 39.9754)`
* -r 25: `XPSNR  y: 41.3326  u: 39.9754  v: 42.0654  (minimum: 39.9754)`
* -r 29.98: `XPSNR  y: 41.3326  u: 39.9754  v: 42.0654  (minimum: 39.9754)`
* -r 30: `XPSNR  y: 41.3326  u: 39.9754  v: 42.0654  (minimum: 39.9754)`
* -r 59.94: `XPSNR  y: 41.4567  u: 40.1164  v: 42.1757  (minimum: 40.1164)`
* -r 60: `XPSNR  y: 41.4567  u: 40.1164  v: 42.1757  (minimum: 40.1164)`
* -r 119.88: `XPSNR  y: 41.4567  u: 40.1164  v: 42.1757  (minimum: 40.1164)`
* -r 120: `XPSNR  y: 41.4567  u: 40.1164  v: 42.1757  (minimum: 40.1164)`
* -r 240: `XPSNR  y: 41.4567  u: 40.1164  v: 42.1757  (minimum: 40.1164)`


### pixabay-nature-31377.sample4+480f.mkv vs pixabay-nature-31377.sample4+480f.av1.crf25.10.mp4
ref:   `Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](und): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, bt709, progressive), 3840x2160, 119304 kb/s, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 24k tbn (default)`

* No -r: `XPSNR  y: 28.9671  u: 48.3898  v: 47.8256  (minimum: 28.9671)`
* -r 23.98: `XPSNR  y: 41.0996  u: 50.3653  v: 50.1395  (minimum: 41.0996)`
* -r 25: `XPSNR  y: 41.0996  u: 50.3653  v: 50.1395  (minimum: 41.0996)`
* -r 29.98: `XPSNR  y: 41.0996  u: 50.3653  v: 50.1395  (minimum: 41.0996)`
* -r 30: `XPSNR  y: 41.0996  u: 50.3653  v: 50.1395  (minimum: 41.0996)`
* -r 59.94: `XPSNR  y: 41.4735  u: 50.7310  v: 50.5317  (minimum: 41.4735)`
* -r 60: `XPSNR  y: 41.4735  u: 50.7310  v: 50.5317  (minimum: 41.4735)`
* -r 119.88: `XPSNR  y: 41.4735  u: 50.7310  v: 50.5317  (minimum: 41.4735)`
* -r 120: `XPSNR  y: 41.4735  u: 50.7310  v: 50.5317  (minimum: 41.4735)`
* -r 240: `XPSNR  y: 41.4735  u: 50.7310  v: 50.5317  (minimum: 41.4735)`

### 4kmedia-spacex-launch-demo.sample53+600f.mkv vs 4kmedia-spacex-launch-demo.sample53+600f.av1.crf25.10.mp4 
ref:   `Stream #0:0: Video: h264 (High), yuv420p(progressive), 3840x2160 [SAR 1:1 DAR 16:9], 29.98 fps, 29.98 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](und): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 3840x2160, 2004 kb/s, SAR 1:1 DAR 16:9, 29.98 fps, 29.98 tbr, 16308 tbn (default)`

* No -r: `XPSNR  y: 41.4112  u: 43.1899  v: 43.1007  (minimum: 41.4112)`
* -r 23.98: `XPSNR  y: 42.3375  u: 43.3096  v: 43.2075  (minimum: 42.3375)`
* -r 25: `XPSNR  y: 42.3375  u: 43.3096  v: 43.2075  (minimum: 42.3375)`
* -r 29.98: `XPSNR  y: 42.3375  u: 43.3096  v: 43.2075  (minimum: 42.3375)`
* -r 30: `XPSNR  y: 42.3375  u: 43.3096  v: 43.2075  (minimum: 42.3375)`
* -r 59.94: `XPSNR  y: 42.4780  u: 43.4518  v: 43.3237  (minimum: 42.4780)`
* -r 60: `XPSNR  y: 42.4780  u: 43.4518  v: 43.3237  (minimum: 42.4780)`
* -r 119.88: `XPSNR  y: 42.4780  u: 43.4518  v: 43.3237  (minimum: 42.4780)`
* -r 120: `XPSNR  y: 42.4780  u: 43.4518  v: 43.3237  (minimum: 42.4780)`
* -r 240: `XPSNR  y: 42.4780  u: 43.4518  v: 43.3237  (minimum: 42.4780)`


### pixabay-sunrise-83880.sample6+2398f.mkv vs pixabay-sunrise-83880.sample6+2398f.av1.crf25.10.mp4 
ref:   `Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 119.88 fps, 119.88 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](eng): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 1920x1080, 2521 kb/s, SAR 1:1 DAR 16:9, 119.73 fps, 119.88 tbr, 29011 tbn (default)`

* No -r: `XPSNR  y: 41.6402  u: 43.1599  v: 43.7515  (minimum: 41.6402)`
* -r 23.98: `XPSNR  y: 41.6516  u: 43.1253  v: 43.7165  (minimum: 41.6516)`
* -r 25: `XPSNR  y: 41.6516  u: 43.1253  v: 43.7165  (minimum: 41.6516)`
* -r 29.98: `XPSNR  y: 41.6516  u: 43.1253  v: 43.7165  (minimum: 41.6516)`
* -r 30: `XPSNR  y: 41.6516  u: 43.1253  v: 43.7165  (minimum: 41.6516)`
* -r 59.94: `XPSNR  y: 41.7000  u: 43.1744  v: 43.7656  (minimum: 41.7000)`
* -r 60: `XPSNR  y: 41.7000  u: 43.1744  v: 43.7656  (minimum: 41.7000)`
* -r 119.88: `XPSNR  y: 41.7000  u: 43.1744  v: 43.7656  (minimum: 41.7000)`
* -r 120: `XPSNR  y: 41.7000  u: 43.1744  v: 43.7656  (minimum: 41.7000)`
* -r 240: `XPSNR  y: 41.7000  u: 43.1744  v: 43.7656  (minimum: 41.7000)`


### pixabay-bridge-23544.sample5+600f.mkv vs pixabay-bridge-23544.sample5+600f.av1.crf25.10.mp4 
ref:   `Stream #0:0: Video: h264 (High), yuv420p(progressive), 3840x2160 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](und): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 3840x2160, 15778 kb/s, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 15360 tbn (default)`

* No -r: `XPSNR  y: 35.2116  u: 44.1664  v: 41.7326  (minimum: 35.2116)`
* -r 23.98: `XPSNR  y: 41.4578  u: 44.8719  v: 42.7145  (minimum: 41.4578)`
* -r 25: `XPSNR  y: 41.4578  u: 44.8719  v: 42.7145  (minimum: 41.4578)`
* -r 29.98: `XPSNR  y: 41.4578  u: 44.8719  v: 42.7145  (minimum: 41.4578)`
* -r 30: `XPSNR  y: 41.4578  u: 44.8719  v: 42.7145  (minimum: 41.4578)`
* -r 59.94: `XPSNR  y: 41.7249  u: 45.1529  v: 43.0079  (minimum: 41.7249)`
* -r 60: `XPSNR  y: 41.7249  u: 45.1529  v: 43.0079  (minimum: 41.7249)`
* -r 119.88: `XPSNR  y: 41.7249  u: 45.1529  v: 43.0079  (minimum: 41.7249)`
* -r 120: `XPSNR  y: 41.7249  u: 45.1529  v: 43.0079  (minimum: 41.7249)`
* -r 240: `XPSNR  y: 41.7249  u: 45.1529  v: 43.0079  (minimum: 41.7249)`


### pixabay-elevator-3735.sample12+500f.mkv vs pixabay-elevator-3735.sample12+500f.av1.crf25.10.mp4 
ref:   `Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](und): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, progressive), 1920x1080, 3981 kb/s, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 12800 tbn (default)`

* No -r: `XPSNR  y: 42.2316  u: 42.4898  v: 43.2556  (minimum: 42.2316)`
* -r 23.98: `XPSNR  y: 42.2316  u: 42.4898  v: 43.2556  (minimum: 42.2316)`
* -r 25: `XPSNR  y: 42.2316  u: 42.4898  v: 43.2556  (minimum: 42.2316)`
* -r 29.98: `XPSNR  y: 42.2316  u: 42.4898  v: 43.2556  (minimum: 42.2316)`
* -r 30: `XPSNR  y: 42.2316  u: 42.4898  v: 43.2556  (minimum: 42.2316)`
* -r 59.94: `XPSNR  y: 42.4655  u: 42.7130  v: 43.4876  (minimum: 42.4655)`
* -r 60: `XPSNR  y: 42.4655  u: 42.7130  v: 43.4876  (minimum: 42.4655)`
* -r 119.88: `XPSNR  y: 42.4655  u: 42.7130  v: 43.4876  (minimum: 42.4655)`
* -r 120: `XPSNR  y: 42.4655  u: 42.7130  v: 43.4876  (minimum: 42.4655)`
* -r 240: `XPSNR  y: 42.4655  u: 42.7130  v: 43.4876  (minimum: 42.4655)`


### 4kmedia-sony-new-york-fashion-demo.sample45+1199f.mkv vs 4kmedia-sony-new-york-fashion-demo.sample45+1199f.av1.crf25.10.mp4 
ref:   `Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 1k tbn (default)`

dist:  `Stream #0:0[0x1](und): Video: av1 (libdav1d) (Main) (av01 / 0x31307661), yuv420p10le(tv, bt2020nc/bt2020/smpte2084, progressive), 3840x2160, 25902 kb/s, SAR 1:1 DAR 16:9, 59.89 fps, 59.94 tbr, 19001 tbn (default)`

* No -r: `XPSNR  y: 32.6134  u: 40.4652  v: 42.5790  (minimum: 32.6134)`
* -r 23.98: `XPSNR  y: 42.1815  u: 41.9205  v: 43.9617  (minimum: 41.9205)`
* -r 25: `XPSNR  y: 42.1815  u: 41.9205  v: 43.9617  (minimum: 41.9205)`
* -r 29.98: `XPSNR  y: 42.1815  u: 41.9205  v: 43.9617  (minimum: 41.9205)`
* -r 30: `XPSNR  y: 42.1815  u: 41.9205  v: 43.9617  (minimum: 41.9205)`
* -r 59.94: `XPSNR  y: 42.8844  u: 42.5356  v: 44.6340  (minimum: 42.5356)`
* -r 60: `XPSNR  y: 42.8844  u: 42.5356  v: 44.6340  (minimum: 42.5356)`
* -r 119.88: `XPSNR  y: 42.8844  u: 42.5356  v: 44.6340  (minimum: 42.5356)`
* -r 120: `XPSNR  y: 42.8844  u: 42.5356  v: 44.6340  (minimum: 42.5356)`
* -r 240: `XPSNR  y: 42.8844  u: 42.5356  v: 44.6340  (minimum: 42.5356)`

</details>
