### ISSUE TITLE
Error: Failed to find a suitable crf

### ISSUE THREAD

**Issue by astalavistababe** [alexheretic/ab-av1#259]
E:\AIapps\Vid_Down_Conv\ab-av1>ab-av1 auto-encode -i "test.mkv" --preset 7 --max-crf 60 --min-crf 21 --min-vmaf 94
Encoding test.av1.mkv
  00:01:01 crf 40 1/1 ########################################################################## (VMAF 92.81, size 134%)Error: Failed to find a suitable crf

E:\AIapps\Vid_Down_Conv\ab-av1>ab-av1 auto-encode -i "test.mkv" --preset 7 --max-crf 45 --min-crf 27 --min-vmaf 94
Encoding test.av1.mkv
  00:01:00 crf 36 1/1 ########################################################################## (VMAF 93.95, size 171%)Error: Failed to find a suitable crf

E:\AIapps\Vid_Down_Conv\ab-av1>ab-av1 auto-encode -i "test.mkv" --preset 8 --max-crf 60 --min-crf 5 --min-vmaf 94
Encoding test.av1.mkv                                                                                                  )  00:01:38 crf 49 1/1 ########################################################################### (VMAF 88.94, size 85%)Error: Failed to find a suitable crf

E:\AIapps\Vid_Down_Conv\ab-av1>ab-av1 auto-encode -i "test.mkv" --preset 8 --max-crf 53 --min-crf 1 --min-vmaf 95
Encoding test.av1.mkv
  00:01:39 crf 43 1/1 ########################################################################## (VMAF 91.28, size 117%)Error: Failed to find a suitable crf

E:\AIapps\Vid_Down_Conv\ab-av1>ab-av1 auto-encode -i "test.mkv" --preset 8 --min-vmaf 94
Encoding test.av1.mkv
  00:00:48 crf 46 1/1 ########################################################################### (VMAF 90.14, size 99%)Error: Failed to find a suitable crf

Any suggestion, and is there any guide to how to use ab-av1?

**Comment by alexheretic** [comment]
crf-search tries to find the best crf value delivering `--min-vmaf` & `--max-encoded-percent` (default 80). If it fails find any such crf you get this error.

So i don't see an issue with this output. It's essentially telling you this video cannot be efficiently re-encoded with these settings.

**Comment by alexheretic** [comment]
Though this does make me wonder if we could improve that error message by explaining more clearly the reason. There is the red colour on the size but the text could also explain why the search ended in failure.
