### ISSUE TITLE
Support multiple encoders for future proofing

### ISSUE THREAD

**Issue by Werve** [alexheretic/ab-av1#37]
I was simply wondering since encoding is currently handled by SVT-AV1 directly and the likely arrival of AV1 hardware encoding on the next generation of video cards if it would not be more future-proof to be able to choose the encoder to use, like using ffmpeg for encoding? 
This way it simply need to have an updated version of ffmpeg to encode in future formats as well (and also for those already present, h264, h265 etc.).
I think that a flag addition to choose to pass commands to ffmpeg for encoding would be enough.

**Comment by alexheretic** [comment]
It would be nice to run comparisons of different encoders all "auto-encoding" + across presets all from ab-av1.

On the other hand the main use case is to use the "best" av1 encoder to re-encode stuff. Just having one makes the code simpler, easier to maintain, the cli easier to design & understand etc.

What kind of use cases were you thinking about?

**Comment by Werve** [comment]
The use case I was referring to is using ffmpeg for encoding while retaining the ab-av1 feature of the VMAF sample to evaluate quality and file size.
Unlike the current version which is based on the svt-av1 encoder then based on the cli flags accepted by the included version of the encoder which could be incompatible with new versions I would entrust the encoding handling to ffmpeg with the advantage of being able to use other encodings as well.

Worst case scenario: ffmpeg changes the syntax and is no longer compatible with the implemented version. So the same fate that could happen in the current state using the SVT-AV1 encoder.

In other cases: You can get the same results as the current ab-av1 version but also more flexibility by being able to choose a different supported encoder that is already included in ffmpeg. This means greatly reducing the need for upgrades for future encoders such as GPU intensive AV1 ones. Also confirming the use case of using the "best" av1 encoder to re-encode stuff.
