### ISSUE TITLE
crf-search leaves terminal broken after exiting

### ISSUE THREAD

**Issue by jbosboom** [alexheretic/ab-av1#41]
In both kitty (my usual terminal) and xterm, after running crf-search, the terminal does not echo typed characters.  This occurs both when crf-search runs to completion and when I interrupt it before it finishes.  When crf-search is writing to a pipe, this occurs when crf-search runs to completion, but not when I interrupt it.  `reset` fixes the terminal, but also empties the scrollback.

ab-av1 0.3.2 built from AUR, kitty 0.25.1-1, xterm 372-2

**Comment by alexheretic** [comment]
I'd guess it could be related to https://github.com/console-rs/indicatif which the binary uses for the fancy progress bars. But I'm not 100%.

I'll try to reproduce if I get some time.

**Comment by alexheretic** [comment]
I haven't been able to reproduce myself. If possible can you see if it occurs with the [console-rs/indicatif](https://github.com/console-rs/indicatif) examples & if so report an issue there.

I've also just updating the main with the latest version of _indicatif_, so may be worth retesting with that.

**Comment by jbosboom** [comment]
I no longer have this problem with ab-av1 0.4.1, so I guess it was a library bug.

**Comment by alexheretic** [comment]
Ah nice, thanks for the update.
