### ISSUE TITLE
Confusing behavior with single quotes in filename

### ISSUE THREAD

**Issue by unrelentingtech** [alexheretic/ab-av1#42]
Just so happened that the video I used for trying this out contained a single quote character :)

```
% ab-av1 crf-search --temp-dir /tmp --preset 8 -i Australia\'s\ 3,488\ Mile\ Long\ Fence-qKX9Oq8UvBI.mkv
[…] Encode with: ab-av1 encode -i "Australia\'s 3,488 Mile Long Fence-qKX9Oq8UvBI.mkv" --crf 48 --preset 8
```

The suggested command uses **both** escaping and double quoting, which is incorrect — it makes zsh pass the escaping slash as a literal slash in the argument…

```
% ab-av1 encode -i "Australia\'s 3,488 Mile Long Fence-qKX9Oq8UvBI.mkv" --crf 48 --preset 8 -o /tmp/test.webm
Error: ffmpeg yuv4mpegpipe exit code Some(1)
```

…and then, seems like ab-av1 doesn't check the input file's existence, leaving that to ffmpeg, and hides ffmpeg's output (#1) so the result is a very unhelpful message.

**Comment by alexheretic** [comment]
Fair point, I've just been using the `Path`/`PathBuf` debug impl as it seemed to mostly work. We can fix this by actually escaping the path for a shell.

And yeah I need to get around to #1 for sure.

**Comment by alexheretic** [comment]
I've added shell escaping for that hint, it'll be in the next release.
