### ISSUE TITLE
Failed to find a suitable crf

### ISSUE THREAD

**Issue by emarleau** [alexheretic/ab-av1#48]
Hello, I'm trying to transcode a 25min video file using the auto-encode command but i'm having an error:

`[emmanuel@arch Videos]$ ab-av1 auto-encode -i 'Passe-Partout S04E18.mp4' --preset 8
Encoding 'Passe-Partout S04E18.av1.mp4'
  Searching 00:16:44 ####################################################################################################### (crf 24, VMAF 94.97, size 105%)
Error: Failed to find a suitable crf`

Here is the file informations:

General

Complete name                            : /home/emmanuel/Videos/Passe-Partout S04E18.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 378 MiB
Duration                                 : 25 min 0 s
Overall bit rate                         : 2 115 kb/s
Writing application                      : Lavf59.16.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 24 min 59 s
Bit rate                                 : 1 914 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.069
Stream size                              : 342 MiB (91%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 25 min 0 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 34.3 MiB (9%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1

**Comment by alexheretic** [comment]
[crf-search](https://github.com/alexheretic/ab-av1#command-crf-search) is an attempt to 

> ...find the best crf value delivering **min-vmaf** & **max-encoded-percent**

The default `--min-vmaf` is **95**, the default `--max-encoded-percent` is **80**. So in your case the search has found that crf 24 doesn't satisfy either and so gives up the search, in this case (at preset 8) there is no crf value that can deliver that quality & compression.

You can, of course, override these defaults and try lower presets. However, in this case I imagine the input video is just already fairly compressed and so difficult to re-encode.

**Comment by emarleau** [comment]
Thanks! I will try with a lower preset.
