### ISSUE TITLE
[Question (Probably dumb)] Where to get SvtAv1EncApp thing?

### ISSUE THREAD

**Issue by HaiziIzzudin** [alexheretic/ab-av1#50]
![image](https://user-images.githubusercontent.com/79714350/189580763-21da90da-bfa6-4a25-aed7-477855d0fe31.png)
So I tried, but it getting error SvtAv1EncApp. How and where can I get it?

Platform: Windows 11 Enterprise IoT
Installation using cargo
Uses powershell terminal (and powershell command)
FFmpeg has been added to PATH, but where to get svtav1encapp?

**Comment by HaiziIzzudin** [comment]
UPDATE: I get the SvtAv1EncApp thing, but it require me to grab others repository (require me to download their repo, which btw super big, about 105MB), and just pull out svtav1encapp thing from their archive to PATH.
Which is not convenient..
Can I know where can I get ONLY the SvtAv1EncApp executable, and nothing else?

**Comment by HaiziIzzudin** [comment]
UPDATE 2: I try to encode to av1 using _other-people-projects-svtav1encapp_ executable, and it failed to play the video when encode finishes. So, clearly I need the actual SvtAv1EncApp executable for it to be working. hmmmmmmmmmm

**Comment by Werve** [comment]
Since ab-av1 version 0.4.0 you can use ffmpeg to encode https://github.com/alexheretic/ab-av1/pull/44 
Otherwise if you want to use the method with SvtAv1EncApp I use the binary available here https://jeremylee.sh/bins/
