### ISSUE TITLE
Something wrong with terminal output after cancelling run

### ISSUE THREAD

**Issue by MillingtonAllen1** [alexheretic/ab-av1#51]
If I run `ab-av1 crf-search --encoder libx264 -i {file} --preset fast` and then cancel the run with Control+C, when I go to type things into terminal, no text appears.  The terminal knows the input is there (ex, if I run echo "Hello World" it does echo), it just doesn't display the text.  It does this in both xterm as well as konsole.

Perhaps there's a better way to clean up better when terminating the program.  This is what I found from searching the issue, not sure if relevant:
https://stackoverflow.com/a/17683085/10709253

**Comment by alexheretic** [comment]
I have managed to reproduce this in a bash shell terminal (xterm + gnome-terminal), but not with fish shell (which would explain why I've never encountered this myself).

Seems the same as https://github.com/alexheretic/ab-av1/issues/41

It could be an edge case / race in the _indicatif_ progress bar printing.

**Comment by alexheretic** [comment]
While I have now seen it happen I can't reproduce it reliably enough to actually test any fixes my end :disappointed:

**Comment by alexheretic** [comment]
Ok I can now reproduce it fairly reliably, by invoking in a loop
```bash
for i in {1..100}; do ab-av1 crf-search -i tmp.mkv; done
```
And sending SIGINT to ab-av1 every 0-3 seconds.

By the end the terminal is trashed & needs to be reset.

I can test fixes for it now...

**Comment by alexheretic** [comment]
Ok I tried totally removing the _indicatif_ crate (progress bars) and it still happens, no more blaming that :sweat_smile:
