### ISSUE TITLE
[Idea] More efficient crf-search in later runs

### ISSUE THREAD

**Issue by iPaulis** [alexheretic/ab-av1#59]
I would like to share an idea for the crf-search part as I believe it could make its execution more efficient.

Some users, like myself, might re-run the crf-search with a slightly different vmaf target if the initial target does not give a desirable result. 
Have you considered saving those crf-search test results internally for a more efficient execution of ab-av1 in a later run?

If ab-av1 had a history of results saved of the latest/recently analyzed files, and the user wanted to crf-search again a previously analyzed file with the same preset, having the crf/vmaf results of the previous binary search of that same file would narrow down the attempts to crf-search the new target vmaf, thus getting the crf-search result faster for the new target vmaf. 

It could potentially save up a lot of time, specially for large files in lower presets, by improving the internal logic of crf-search thanks to previously saved results.

**Comment by alexheretic** [comment]
I touched on a similar idea in https://github.com/alexheretic/ab-av1/issues/49#issuecomment-1220972970

> Another idea is to be able to save crf-search results in a file and re-use them on subsequent runs. It would only work using the same encoder & any encoder args though, so not as flexible an idea as it may first appear.

I think it probably is worth investigating further, but there are some details to getting it right which, I think, makes it a non-trivial addition.

**Comment by iPaulis** [comment]
Yeah, I think it might be a big improvement for many of us that are learning and tinkering how the different encoders and crf scales behave.

Thank you for considering the idea.
