### ISSUE TITLE
Windows: Add unix fifo-pipe equivalent so vmaf distorted can be converted to the same pixel format

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/ab-av1#65]
On Linux a fifo file pipe is used during VMAF so both reference and distorted files can be converted into a yuv stream in the same way before passing to VMAF.

Windows does not support fifo, so currently not conversion is being done on the distorted. This means Windows vmaf scores suffer. Ideally windows would do the same thing.

Linux impl: https://github.com/alexheretic/ab-av1/blob/37272016bf0d471fea67c90b24a0545a95aebe62/src/yuv.rs#L45..L70

**Comment by alexheretic** [comment]
https://github.com/alexheretic/ab-av1/issues/63#issuecomment-1314953259

Perhaps _interprocess_ unnamed pipes could also work?

**Comment by alexheretic** [comment]
I've had a look but I can't get a fifo-like to work on Windows. I just don't really understand how to use the named-pipe/sockets available there.

**Comment by BankaiNoJutsu** [comment]
I'm not knowledgeable enough for trying this out, but here's another
possible solution, as it seems to be cross platform.

https://crates.io/crates/ipipe

**Comment by iPaulis** [comment]
Sorry, I'm not a programmer, I have no idea about rust and I'm not familiar with those concepts. I had a look at that part of the code and I didn't understand much.

But if there is a possible solution I could test it out and report the results.

I wish I could be of more help.

**Comment by alexheretic** [comment]
Turns out tokio has built-in support for windows named pipes. I got it to work by creating 2 pipes and an async task to copy between them. It's much simpler using fifo on Linux!
