### ISSUE TITLE
[Question/Suggestion] Pre-compiled ab-av1.exe

### ISSUE THREAD

**Issue by HaiziIzzudin** [alexheretic/ab-av1#75]
I see that ab-av1 is built from source, and the executable ab-av1.exe is put under .cargo directory.
Just asking, if devs can offer a pre-built ab-av1.exe in your Release, cause building from source require installation of rustup and Visual Studio + cpp development, which costs ~8GB in installation size. RIP my mobile data, and storage.

**Comment by alexheretic** [comment]
It should be possible to add a windows compiled version via github actions ci on each tag.

**Comment by alexheretic** [comment]
**ab-av1.exe** builds will be available on new releases, e.g. https://github.com/alexheretic/ab-av1/releases/tag/v0.5.0
