### ISSUE TITLE
Almost immediate panic on `crf-search` subcommand

### ISSUE THREAD

**Issue by redzic** [alexheretic/ab-av1#8]
```
redzic@threadripper ~/P/ab-av1 (main)> ./target/release/ab-av1 crf-search -i input.y4m --preset 8
⠉ 00:00:00 -------------------------------------------------------------------------------------------------------------------------- (sampling crf 32, eta 0s)
thread 'main' panicked at 'non-finite value when converting float to duration', /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/time.rs:735:23
Error: panic
```

This is on commit d96b6bd1779b423137ab53568821810a0e5a0392, compiled with rustc 1.58.1.

**Comment by alexheretic** [comment]
Thanks, can you run with `RUST_BACKTRACE=1` or provide a link to the input file?

**Comment by alexheretic** [comment]
Thanks for the info. This happens as sample-encode doesn't currently handle the case when the input is of a small duration yet, particularly below the sample size of 20 seconds.

We can handle this as a special case and just encode & vmaf the full video.

**Comment by alexheretic** [comment]
I've pushed a fix so that **sample-encode** will simply use the entire input duration in the case that is shorter than the sample duration. Let me know if that works for you.

**Comment by redzic** [comment]
It does work, thanks!
