### ISSUE TITLE
[Suggestion] Allow decimal crf values

### ISSUE THREAD

**Issue by iPaulis** [alexheretic/ab-av1#83]
Hi, I was wondering if it would be possible to allow to introduce decimal crf values, for example when running sample-encode to check a specific crf value (--crf 19.5). Similar to how we can now introduce target vmaf in crf-search with decimal values (--min-vmaf 93.5). 

There are 2 main reasons why this could be of interest.
First is that some encoders, such as svt-av1, seem more granular in their vmaf/crf progression, but some others, like x265, may have quite big jumps in vmaf values and predicted sizes with only 1 point difference in crf.
It is quite common in x264 and x265 to have files encoded with decimal crf values, and even an 0,5 crf difference may result in an encoded file size 10-15% smaller/bigger.
Handbrake and other encoders allow decimal crf values, so many of my current encodes do not have integer crf values, and I'm trying to establish equivalences between the new encoders, new encoding methods and my current files thanks to ab-av1, so being able to use decimal values would be helpful.

Secondly, for some files this way of treating crf as an integer could make ab-av1 have more difficulties searching the crf for a given target vmaf, having to test more crf values, thus taking longer to finish. Besides, sometimes the recommended final crf results in a vmaf value further from target than usual, because crf -1 would result in an vmaf value just a bit lower than the minimum required.

```
ab-av1 crf-search -e libx265 --enc x265-params=psy-rd=0.00 --pix-format yuv420p10le --min-vmaf 93 --vmaf 
pool=harmonic_mean --vmaf n_threads=16 -i '.\testfile2.mp4' --preset 5
```
> - crf 32 VMAF 78.46 (7%)
> - crf 21 VMAF 96.99 (28%)
> - crf 23 VMAF 95.20 (22%)
> - crf 24 VMAF 94.07 (19%)
> - crf 25 VMAF 92.79 (17%)
> crf 24 VMAF 94.07 predicted video stream size 243.46 MiB (19%) taking 15 minutes

So in this example targeting vmaf 93 or 94 would result in the same recommended crf 24. For min-vmaf 93 a crf value of 24,5 would have been better, and leave crf 24 to achieve vmaf 94. 
Allowing decimal crf values could improve the internal logic of ab-av1 and offer more accurate vmaf results and higher encoding size savings.

Another example:
```
ab-av1 crf-search -e libx265 --enc x265-params=psy-rd=0.00 --enc x265-params=lookahead-slices=5 --pix-format yuv420p10le 
--min-vmaf 92 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i '.\test3.mp4' --preset 5
```
> - crf 32 VMAF 72.08 (7%)
> - crf 21 VMAF 93.96 (28%)
> - crf 22 VMAF 92.81 (24%)
> - crf 23 VMAF 91.48 (21)
> crf 22 VMAF 92.81 predicted video stream size 318.87 MiB (24%) taking 13 minutes

That's 1,33 vmaf score difference just from crf 22 to 23, quite a bit.

What do you think of the idea? would it be possible?

**Comment by alexheretic** [comment]
Yep it's possible, perhaps starting with a single decimal place and using similar logic.

The main drawback is that svt-av1 only support integer crf so this work won't provide any value there.

**Comment by iPaulis** [comment]
Sounds good.
svt-av1 does not need decimal values anyway, they seem to have designed it to be usable across a greater range of crf with less impact in quality/vmaf. 
In my testing, even 2-3 points difference in crf results only in about +-0,2 to 0,3 vmaf score difference in av1, but x265 and x264 are a complete different story, as shown above, they would benefit from decimal values.

**Comment by alexheretic** [comment]
The current crf search is really designed for svt-av1. But it could be generalized to allow configurable min, max and precision. That sounds worth a try though it will probably make the code more complex.

**Comment by iPaulis** [comment]
Trying to keep it as simple as possible initially, could it be possibe to allow decimal crf values in sample-encode just for x265 and 264? there is no crf-search involved in there, right? so it could be not as complicated to allow that?

It has just to encode using that given crf value and give a resulting vmaf score, as it does right now, but allowing to introduce a decimal crf value, right?

Could we start with this and then leave the more complex changes in crf-search for later?

**Comment by alexheretic** [comment]
#87 implements this. Needs some more testing.
