### ISSUE TITLE
`crf-search` panics almost immediately on any file

### ISSUE THREAD

**Issue by zeko9381** [alexheretic/ab-av1#86]
Hello,
I've installed `ab-av1` using `cargo install --git https://github.com/alexheretic/ab-av1` to make sure I have the latest version. When I try running the command `~/.cargo/bin/ab-av1 crf-search -i test.mp4 --preset 6` the task panics after 10-40 seconds on any video file.
Here is the error with the stack trace:
```
thread 'main' panicked at 'can not convert float seconds to Duration: value is either too big or NaN', /builddir/build/BUILD/rustc-1.65.0-src/library/core/src/time.rs:736:23
stack backtrace:
   0:     0x55c792d5c889 - <unknown>
   1:     0x55c792d08dae - <unknown>
   2:     0x55c792d335c4 - <unknown>
   3:     0x55c792d5d813 - <unknown>
   4:     0x55c792d5e74d - <unknown>
   5:     0x55c792d5e312 - <unknown>
   6:     0x55c792d5e27c - <unknown>
   7:     0x55c792d5e251 - <unknown>
   8:     0x55c792c66e42 - <unknown>
   9:     0x55c792c80936 - <unknown>
  10:     0x55c792c8f2c1 - <unknown>
  11:     0x55c792cab021 - <unknown>
  12:     0x55c792c873ef - <unknown>
  13:     0x55c792cb6786 - <unknown>
  14:     0x55c792ca6560 - <unknown>
  15:     0x55c792cb5aa7 - <unknown>
  16:     0x7f98b7cc7510 - __libc_start_call_main
  17:     0x7f98b7cc75c9 - __libc_start_main_alias_2
  18:     0x55c792c6a195 - <unknown>
  19:                0x0 - <unknown>

```
I'm running Fedora 37, if that's important.

**Comment by zeko9381** [comment]
Running `sample-encode` throws the same error, so it looks like it's a similar issue to #8.

**Comment by zeko9381** [comment]
Just tested the 0.5.0 release and it works fine.

**Comment by alexheretic** [comment]
Thanks for the report. Since v0.5.0 we started ffprobing the encoded samples, so it looks like they have an invalid duration for you.

I've pushed a fix to main that should avoid this panicking b4acad00e9b9fa9fb620d20e78e66bc3018e0a0a. Can you re-try?

**Comment by zeko9381** [comment]
Nope, the result is the same.
```
thread 'main' panicked at 'can not convert float seconds to Duration: value is either too big or NaN', /builddir/build/BUILD/rustc-1.65.0-src/library/core/src/time.rs:736:23
stack backtrace:
   0:     0x559001e189e9 - <unknown>
   1:     0x559001dc4e4e - <unknown>
   2:     0x559001def654 - <unknown>
   3:     0x559001e19973 - <unknown>
   4:     0x559001e1a8ad - <unknown>
   5:     0x559001e1a472 - <unknown>
   6:     0x559001e1a3dc - <unknown>
   7:     0x559001e1a3b1 - <unknown>
   8:     0x559001d22e82 - <unknown>
   9:     0x559001d46a37 - <unknown>
  10:     0x559001d45bc2 - <unknown>
  11:     0x559001d61c49 - <unknown>
  12:     0x559001d3dbf4 - <unknown>
  13:     0x559001d738a6 - <unknown>
  14:     0x559001d5cfc3 - <unknown>
  15:     0x559001d72bc7 - <unknown>
  16:     0x7f08f0360510 - __libc_start_call_main
  17:     0x7f08f03605c9 - __libc_start_main_alias_2
  18:     0x559001d261d5 - <unknown>
  19:                0x0 - <unknown>
```

**Comment by alexheretic** [comment]
Thanks for retesting. 

Can you re-build with `RUSTFLAGS='-C strip=none' cargo install --git https://github.com/alexheretic/ab-av1` so the stack trace will have all the symbols. That could be helpful for zeroing in on what's panicking.

**Comment by alexheretic** [comment]
I've had another look and this could possibly be caused by, rather than an invalid, a **zero** ffprobe duration of the encoded samples. I can fix that scenario by ignoring zero in that case, please try the latest commit [bc2bd5d](https://github.com/alexheretic/ab-av1/commit/bc2bd5d1fea5ef26bfcba3500f05315f62faa808).

**Comment by zeko9381** [comment]
It works now. Thank you, wizard!
