### ISSUE TITLE
Compilation error in v0.6.1 build

### ISSUE THREAD

**Issue by iPaulis** [alexheretic/ab-av1#96]
Hi, I just tried to compile the latest released version v0.6.1 and this error appeared:

> error[E0658]: use of unstable library feature 'duration_checked_float'
>   --> src\ffprobe.rs:99:13
>    |
> 99 |             Duration::try_from_secs_f64(duration_f)
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    |
>    = note: see issue #83400 <https://github.com/rust-lang/rust/issues/83400> for more information
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `ab-av1` due to previous error

This problem was introduced in this version, the previous one gave no error to compile.

**Comment by alexheretic** [comment]
I made use of a new std function in recently released rust 1.66.

This actually shouldn't apply to v0.6.1 itself but does to the main git branch and future releases.

Run `rustup update` to update rustc.

**Comment by iPaulis** [comment]
Thanks, fixed.
