### ISSUE TITLE
Display Resolution is Not Preserved

### ISSUE THREAD

**Issue by georgemcarlson** [alexheretic/ab-av1#97]
Love the tool but it does not preserve aspect ratio metadata so I currently need to modify the files afterwards.

Input video: 960x480,SAR 119:134, DAR 119:67
Output video: 960x480, SAR 1:1 DAR 2:1

**Comment by alexheretic** [comment]
Hmm, there's nothing specific here that would cause this, at least that I can think of.

Can you try using `-e libx265` (to rule out svt-av1 encoder). If that still does it it must be an ffmpeg thing.

Try using ffmpeg directly and seeing if it occurs that way, if so maybe there are workarounds?

**Comment by georgemcarlson** [comment]
I can confirmed that this did not happen with `--encoder libx264`

```
Input video: 960x480, SAR 479:538, DAR 479:269
Output Video: 960x480, SAR 479:538, DAR 479:269
```

Same video ran with `--encoder svt-av1`:

```
Input video: 960x480, SAR 479:538, DAR 479:269
Output Video: 960x480, SAR 1:1 DAR 2:1
```

I also tried the same video with `--encode svt-av1 --vfilter "setdar=dar=1.777"`:

```
Input video: 960x480, SAR 479:538, DAR 479:269
Output Video: 960x480, SAR 1:1 DAR 2:1
```

> if so maybe there are workarounds?

For personal use I can write a script that just sets the output dar to be the input dar after the encode is done. But having the dar change with no specification to change it and not being able to force a dar with `--vfilter "setdar=dar=#.###"` is unexpected.

**Comment by georgemcarlson** [comment]
> Try using ffmpeg directly and seeing if it occurs that way, if so maybe there are workarounds?

SvtAv1EncApp does not keep track of a DAR, all pixels are square. So, when the video stream from SvtAv1EncApp is sent to FFMPEG there is no display aspect ratio included. This is not affecting the `libx264` and `libx265` encoding options because those are both handled entirely within an FFMPEG call so FFMPEG can get the display aspect video from the input video.

I have not found a way to set the `-aspect` parameter from a mapped input video stream. Adding a `.arg2("-aspect", var)` to line https://github.com/alexheretic/ab-av1/blob/main/src/svtav1.rs#L164 would where var is a passed in as a command argument would help. I am not at all familiar with the Rust programming language but it I think the following sudo-code would completely fix this issue.

```
	let dar = Command::new("ffprobe")
        .kill_on_drop(true)
        .arg2("-v", "error")
        .arg2("-select_streams", "v:0")
        .arg2("-of", "default=noprint_wrappers=1:nokey=1")
        .arg2("-show_entries", "stream=display_aspect_ratio")
        .arg2(input)

    let to_output = Command::new("ffmpeg")
        .kill_on_drop(true)
        .arg("-y")
        .arg2("-i", "-")
        .arg2("-i", input)
        // use av1 video
        .arg2("-map", "0:v")
        // map everything but video from input
        .arg2("-map", "1")
        .arg2("-map", "-1:v")
        .arg2("-c:s", "copy")
        .arg2("-c:a", audio_codec)
        .arg2_if(downmix_to_stereo, "-ac", 2)
        .arg2("-c:v", "copy")
        .arg2("-aspect", dar)
        .arg2_if(audio_codec == "libopus", "-b:a", "128k")
        .arg2_if(add_faststart, "-movflags", "+faststart")
        .arg2_if(add_cues_to_front, "-cues_to_front", "y")
        .arg(output)
        .stdin(svt_out)
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
        .context("ffmpeg to-output")?;
```

**Comment by alexheretic** [comment]
Thanks, another option might be invoking svt-av1 through ffmpeg in the same way other encoders are. Previously it wasn't possible to pass svt-av1 args that way, so SvtAv1EncApp is called directly, but in recent ffmpeg versions it's possible.

This should address this issue by letting ffmpeg handle it. I just need to test that this path will work properly.

**Comment by alexheretic** [comment]
You can also test this path out by replacing `--preset N` with `--preset N -e libsvtav1 --pix-format yuv420p10le` to use the ffmpeg path.

**Comment by alexheretic** [comment]
Can you try #98 and see if it solves this issue?

**Comment by iPaulis** [comment]
I have some doubts about how this would work. 
If ab-av1 uses ffmpeg libsvtav1 by default, I guess it means that the svtav1 version used is the one implemented in the ffmpeg version we have installed, is that correct? 
How can we know what version of svtav1 is included in our ffmpeg version?
Will we still be able to run ab-av1 with SvtAv1EncApp like we do now? 
I was compiling SvtAv1EncApp directly from their gitlab to take advantage of the latest updates, it would be a pity having to wait for ffmpeg to release a new version that includes an updated svtav1 version. 

Besides, I was also trying to keep ffmpeg more regularly updated with some auto-builds, but have stopped doing so because it started to mess with ab-av1 sample split duration being absolutely inconsistently reported and very unreliable (for example, samples reported as 1h33m, or 15m, etc. very weird stuff that was resulting in nonsensical estimations). I tested with many different files, some were not so bad as others, but it seemed random and was overall unusable, until I found out that the only thing that had changed in my system was ffmpeg (a couple of weeks ago), so I rolled back to a previous version and the problem disappeared. Now I'm sticking to this build from 31st of October, it works great and I'd rather not touch it for a while, just in case.

**Comment by alexheretic** [comment]
> If ab-av1 uses ffmpeg libsvtav1 by default, I guess it means that the svtav1 version used is the one implemented in the ffmpeg version we have installed, is that correct?

On linux it'll be the same version as SvtAvtEncApp it'll be dynamically linked, at least it is on Arch. If using a statically linked ffmpeg build it'll just be whatever they used, presumably a recent version in a recent build.

> Will we still be able to run ab-av1 with SvtAv1EncApp like we do now?

In #98 no, I've removed the code. It's a win for code complexity as we'll no longer have 2 paths for encoding so I like it from that point of view. That it also fixes these aspect issues is another nudge in that direction.

> it would be a pity having to wait for ffmpeg to release a new version that includes an updated svtav1 version.

ffmpeg don't need to release a new version for regular non-breaking updates, if statically linked ffmpeg will need to be rebuilt.

Overall I think it'll be worth unifying the encoder logic, but I'll do some more testing. @iPaulis if you have time take #98 for a spin and see if there are issues for your use case.

**Comment by alexheretic** [comment]
We can add install steps to the readme or more detailed stuff to the [wiki](https://github.com/alexheretic/ab-av1/wiki).

On the other hand perhaps I've underestimated how easy it is to have ffmpeg setup with libsvtav1 (while it is indeed very easy on Arch). Perhaps that means we should hold fire on this change for a while, or add a fallback to the existing behaviour, though that would mean more code rather than less.

**Comment by iPaulis** [comment]
It sure seems way simpler in linux and its users are generally more willing or used to deal with this kind of things. For me this is not an issue either, but most windows or mac users probably won't know or want to bother compiling on their own, and that would greatly limit the number of users that could benefit from this tool.

I've been looking a little bit how it works for windows and I'm not so sure about shared libraries for the shared version of ffmpeg, but it is quite easy to find static builds that automatically include the latest library updates directly compiled from their github/gitlab repositories. So the svtav1 version included in those builds are the most updated ones according to the build date, which is nice.
There are many repositories storing this kind of builds, here is one that regularly updates not only ffmpeg including libsvtav1, but also SvtAvtEncApp among other binaries: https://jeremylee.sh/bins/

It may be helpful for windows users to include a link next to the requirements to meet the dependencies with downloadable binaries as an easier way than having to compile them yourself. Using [Media Autobuild Suite](https://github.com/m-ab-s/media-autobuild_suite) seems the next easiest way to compile, which is a more automated and simple way of compiling these resources without needing to install cmake, microsoft c compilers, etc. on your own.
The only disadvantage of these builds is that they are compiled from the master branch, so they might not be as stable as some frozen release versions could be. I've had problems with some of those builds and ab-av1, maybe a bug was introduced, I have no idea, I'm just speculating, so I had to rollback and have not followed up.

As @georgemcarlson was explaining, there are not so many available premade/easy resources for mac, and there is also the added complexity between the intel x86 and apple silicon arm processors, so mac users might be forced to compile and would have more prerequisites to do so.

**Comment by alexheretic** [comment]
I've merged the change, as I think its the best way forward.

I think we could add some links in the readme to ffmpeg build locations for Linux, Windows & Mac to be helpful.
