### ISSUE TITLE
Encoding images with SvtAv1EncApp sometimes produces unexpected results

### ISSUE THREAD

**Issue by Pyroglyph** [alexheretic/ab-av1#99]
The title of this issue is pretty vague, but I've had numerous different problems with using the default `SvtAv1EncApp` mode.

I first found that there was a problem with an image I was trying to encode when I could view it in Windows Photo Viewer but Chromium could not load it for some reason. Other encoders such as `libaom-av1` and `libsvtav1` did not have this issue and the image was able to be loaded and displayed properly in a browser.

I did test another image to see if I could give a reproducible sample but something else went wrong instead. This time the image was able to be loaded in my browser but it flickered as if it was showing the image and then a white frame over and over again. The other encoders correctly did not show this flickering.

Here are the source and output images for both issue types. All were encoded at CRF 10. No other options were changed (other than the encoder). I would have embedded them into the issue, but GitHub has yet to add support for AVIF uploads.

[images.zip](https://github.com/alexheretic/ab-av1/files/10288498/images-2.zip)

For clarity:
Source image = `.png`
`SvtAv1EncApp` = `.av1.avif`
`libsvtav1` = `.svtav1.avif`
`librav1e` = `.rav1e.avif`

**Comment by alexheretic** [comment]
I'm not 100% sure why, but I'd guess we're not invoking SvtAv1EncApp properly for images.

I am planning on moving away from using SvtAv1EncApp at all (#98) which sounds like it will also address this issue?

Can you try #98 and verify that?

**Comment by Pyroglyph** [comment]
That branch fixes both issues!
Is there a difference between `.av1.ext` and `.svtav1.ext` now that `SvtAv1EncApp` is no longer in use?

**Comment by alexheretic** [comment]
There is not. That branch removes all direct handling of SvtAv1EncApp using ffmpeg's integration instead.

**Comment by Pyroglyph** [comment]
I was asking because now if you don't specify an encoder we get FFmpeg's SVT-AV1 encoder by and a `.av1.ext` extension, but if we pass `--encoder libsvtav1` we use the exact same encoder (and get the exact same output) but the output filename has changed to `.svtav1.ext`, which is mildly confusing.

**Comment by alexheretic** [comment]
That shouldn't be the case, in #98 libsvtav1 should result in .av1 however it's specified.

**Comment by Pyroglyph** [comment]
Ah, my bad. I probably just did the command wrong.
But even so, consider this:
The filename convention we have is `.encoder.ext`, yet it's now no longer obvious from the filename that SVT-AV1 was used to encode a file, meaning that naming convention is being broken. I understand that `.av1.ext` looks a lot cleaner than `.svtav1.ext`, but I do think sticking to the convention will cause less confusion.

**Comment by alexheretic** [comment]
I guess `.av1.ext` means you used the default av1 encoder which is svt-av1. I don't think I'll change this. It's also easy enough to override by specifying an output filename.
